/*
	deobf_rules are detected strings within the module that help determine which module it is.
	Regex is also supported: Start off the string with *** to activate Regex mode

	Don't forget: these are processed BEFORE the beautification process,
	so spaces and tabs (outside of strings) won't be there
*/

exports.deobf_rules = {
	// "babel-index.3.js":"hasInstance,isConcatSpreadable,iterator,match,replace,search,species,split,toPrimitive,toStringTag,unscopables",
	"components.AccountSelector.js": "TD.components.AccountSelector=a",
	"components.ActionDialog.js": "TD.components.ActionDialog=TD.components.",
	"components.AddToListsDialog.js": "TD.components.AddToListsDialog=TD.components.",
	"components.AddToCustomTimelineDialog.js": "TD.components.AddToCustomTimelineDialog=TD.components.",
	"components.Autocomplete.js": "TD.components.Autocomplete=TD.components.",
	"components.BaseModal.js": "TD.components.BaseModal=TD.components.",
	"components.ConversationDetailView.js": "TD.components.ConversationDetailView=TD.components.",
	"components.CustomTimelines.js": "TD.components.CustomTimelines=TD.components.",
	"components.Dataminr.js": "TD.components.Dataminr=TD.components.",
	"components.DataminrDetailView.js": "TD.components.DataminrDetailView=TD.components.",
	"components.DetailView.js": "TD.components.DetailView=TD.components.",
	"components.GlobalSettings.js": "TD.components.GlobalSettings=TD.components.",
	"components.LiveVideos.js": "TD.components.LiveVideos=TD.components.",
	"components.InReplyTo.js": "TD.components.InReplyTo=TD.components.",
	"components.ListMember.js": "TD.components.ListMember=TD.components.",
	"components.ListMemberList.js": "TD.components.ListMemberList=TD.components.",
	"components.ListMembers.js": "TD.components.ListMembers=TD.components.",
	"components.MediaGallery.js": "TD.components.MediaGallery=TD.components.",
	"components.MenuItem.js": "TD.components.MenuItem=TD.components.",
	"components.MenuItemBase.js": "TD.components.MenuItemBase=TD.components.",
	"components.NewFeaturesSplash.js": "TD.components.NewFeaturesSplash=TD.components.",
	"components.OpenColumn.js": "TD.components.OpenColumn=TD.components.",
	"components.OpenColumnHome.js": "TD.components.OpenColumnHome=TD.components.",
	"components.OpenColumnPlaceholder.js": "TD.components.OpenColumnPlaceholder=TD.components.",
	"components.OpenCustomTimelines.js": "TD.components.OpenCustomTimelines=TD.components.",
	"components.OpenDataminr.js": "TD.components.OpenDataminr=TD.components.",
	"components.OpenLiveVideo.js": "TD.components.OpenLiveVideo=TD.components.",
	"components.OpenSplitMenu.js": "TD.components.OpenSplitMenu=TD.components.",
	"components.OpenTwitterGeneric.js": "TD.components.OpenTwitterGeneric=TD.components.",
	"components.ProfileAccount.js": "TD.components.ProfileAccount=TD.components.",
	"components.RepliesTo.js": "TD.components.RepliesTo=TD.components.",
	"components.ReplyBar.js": "TD.components.ReplyBar=TD.components.",
	"components.ScheduledDatePicker.js": "TD.components.ScheduledDatePicker=TD.components.",
	"components.SearchInput.js": "TD.components.SearchInput=TD.components.",
	"components.SelfAccounts.js": "TD.components.SelfAccounts=TD.components.",
	"components.SplitMenu.js": "TD.components.SplitMenu=TD.components.",
	"components.SuggestedUsers.js": "TD.components.SuggestedUsers=TD.components.",
	"components.TemporaryColumn.js": "TD.components.TemporaryColumn=TD.components.",
	"components.TweetDetailView.js": "TD.components.TweetDetailView=TD.components.",
	"components.TwitterUserSearch.js": "TD.components.TwitterUserSearch=TD.components.",
	"constants.js":"TD.constants={",
	"controller.columnManager.js": "TD.controller.columnManager=function(",
	"controller.upgrade.js": "TD.controller.upgrade=(",
	"core.base64.js": "TD.core.base64=function(",
	"core.sha1.js": "TD.core.sha1=function(",
	"decider.js": "TD.config.decider_overlay=(0,r.default)(TD.config.decider_overlay||{}",
	"flight.js": "/*! Flight v",
	"globalRenderOptions.js": "TD.globalRenderOptions=(n={",
	"jquery.js": "Sizzle CSS Selector Engine",
	"jquery.tools.dateinput.js": "Dateinput - <input type=\"date\" />",
	"leaflet-src.js": "return!this._container.getElementsByClassName(\"leaflet-zoom-animated\").length",
	"mapbox.js": "\"leaflet-control-mapbox-geocoder leaflet-bar leaflet-control\"",
	"metrics.js":"TD.metrics=function()",
	"modernizr.prefixed.js":"TRANSITION_END:n({transition:\"transitionend\",",
	"moment.js": "&&!e.invalidMonth&&!e.invalidWeekday",
	"minWrapperVersion.js": "TD.minWrapperVersionMac=\"",
	"object-assign.js": "(c) Sindre Sorhus",
	"react-dom-native-dependencies.js": "* react-dom-native-dependencies",
	"react-dom.js": "* react-dom.production.",
	"react-native.i18nManager.js": "i.default.canUseDOM&&document.documentElement&&document.documentElement.setAttribute&&document.documentElement",
	"react.js": "* react.production.",
	"react.scheduler.js": "* scheduler.production.",
	"services.bitly.js": "TD.services.bitly=((",
	"services.Conversations.js": "TD.services.Conversations=function(",
	"services.CustomTimeline.js": "TD.services.CustomTimeline=function(",
	"services.DataminrAlert.js": "TD.services.DataminrAlert=function(",
	"services.ScheduledTweet.js": "TD.services.ScheduledTweet=function(",
	"services.ScheduledTweetGroup.js": "TD.services.ScheduledTweetGroup=u,",
	"services.TweetDeckClient.js": "TD.services.TweetDeckClient=function(",
	"services.TwitterClient.js": "TD.services.TwitterClient.prototype.processDeleteChirpEvent",
	"services.TwitterActionFavoritedInteraction.js": "TD.services.TwitterActionFavoritedInteraction=function(e",
	"services.TwitterActionFavorite.js": "TD.services.TwitterActionFavorite=function(e",
	"services.TwitterAction.js": "TD.services.TwitterAction=function(e",
	"services.TwitterActionListCreated.js": "TD.services.TwitterActionListCreated=function(e",
	"services.TwitterActionListMemberAdded.js": "TD.services.TwitterActionListMemberAdded=function(e",
	"services.TwitterActionFollow.js": "TD.services.TwitterActionFollow=function(e",
	"services.TwitterActionQuotedTweet.js": "TD.services.TwitterActionQuotedTweet=function(e",
	"services.TwitterActionMultiListMemberAdded.js": "TD.services.TwitterActionMultiListMemberAdded=function(e",
	"services.TwitterActionMention.js": "TD.services.TwitterActionMention=function(e",
	"services.TwitterActionOnTweet.js": "TD.services.TwitterActionOnTweet=function(e",
	"services.TwitterActionRetweet.js": "TD.services.TwitterActionRetweet=function(e",
	"services.TwitterActionRetweetedInteraction.js": "TD.services.TwitterActionRetweetedInteraction=function(e",
	"services.TwitterConversation.js": "TD.services.TwitterConversation=function(",
	"services.TwitterConversationReadEvent.js": "TD.services.TwitterConversationReadEvent=function(e",
	"services.TwitterConversationFailedParticipantsEvent.js": "TD.services.TwitterConversationFailedParticipantsEvent=function(e",
	"services.TwitterDeletedUser.js": "TD.services.TwitterDeletedUser=function(e",
	"services.TwitterList.js": "TD.services.TwitterList=function(e",
	"services.TwitterUser.js": "TD.services.TwitterUser=function(e",
	"services.TwitterSearchParser.js": "TD.services.TwitterSearchParser=function(e",
	"services.TwitterStatus.js": "TD.services.TwitterStatus=function(e",
	"services.TwitterMedia.js": "TD.services.TwitterMedia=function(){}",
	"storage.Account.js": "TD.storage.Account=function(",
	"storage.Client.js": "TD.storage.Client=function(",
	"storage.ClientController.js": "TD.storage.ClientController=(",
	"storage.Column.js": "TD.storage.Column=function(",
	"storage.ColumnController.js": "TD.storage.ColumnController=(",
	"storage.Feed.js": "TD.storage.Feed=(",
	"storage.FeedController.js": "TD.storage.FeedController=(",
	"storage.notification.js": "TD.storage.notification=(",
	"storage.SobjController.js": "TD.storage.SobjController=(",
	"storage.StoredDelta.js": "TD.storage.StoredDelta=function(",
	"storage.StoredObj.js": "TD.storage.StoredObj=function(",
	"sync.controller.js": "TD.sync.controller=function(",
	"ui.column.js": "TD.ui.column={",
	"ui.debug.js": "TD.debug={",
	"ui.main.js": "TD.ui.main=((n={})",
	"ui.openColumn.js": "TD.ui.openColumn=function(",
	"ui.updates.js": "TD.ui.updates=function(",
	"vo.ActionFilter.js": "TD.vo.ActionFilter=function(",
	"vo.Column.js": "TD.vo.Column=function(",
	"vo.EngagementFilter.js": "TD.vo.EngagementFilter=function(",
	"vo.Filter.js": "TD.vo.Filter=function(",
	"vo.SearchFilter.js": "TD.vo.SearchFilter=function("
}
