/*
	deobf_rules are detected strings within the module that help determine which module it is.
	Regex is also supported: Start off the string with *** to activate Regex mode

	Don't forget: these are processed BEFORE the beautification process,
	so spaces and tabs (outside of strings) won't be there
*/

exports.deobf_rules = {
	"assets.fonts.tweetdeck-regular-webfont.woff2.js": `***\\+\\"web\\/assets\\/fonts\\/tweetdeck-regular-webfont\\.[a-f0-9]+\\.woff2`,
	"assets.fonts.tweetdeck-regular-webfont.woff.js": `***\\+\\"web\\/assets\\/fonts\\/tweetdeck-regular-webfont\\.[a-f0-9]+\\.woff(?!2)`,
	"assets.global.backgrounds.default_profile.js": `+"web/assets/global/backgrounds/default_profile.`,
	"assets.global.backgrounds.grad_top_dark.js": `+"web/assets/global/backgrounds/grad_top_dark.`,
	"assets.global.backgrounds.login_bg.js": `+"web/assets/global/backgrounds/login_bg.`,
	"assets.global.backgrounds.migration-arrow.js": `+"web/assets/global/backgrounds/migration-arrow.`,
	"assets.global.backgrounds.spinner-666-on-eee.js": `+"web/assets/global/backgrounds/spinner-666-on-eee.`,
	"assets.global.backgrounds.spinner-888-on-ddd.js": `+"web/assets/global/backgrounds/spinner-888-on-ddd.`,
	"assets.global.backgrounds.spinner-fff-2595be.js": `+"web/assets/global/backgrounds/spinner-fff-2595be.`,
	"assets.global.backgrounds.spinner-fff-on-005675.js": `+"web/assets/global/backgrounds/spinner-fff-on-005675.`,
	"assets.global.backgrounds.spinner-fff-on-198cd8.js": `+"web/assets/global/backgrounds/spinner-fff-on-198cd8.`,
	"assets.global.backgrounds.spinner-fff-on-292F33.js": `+"web/assets/global/backgrounds/spinner-fff-on-292F33.`,
	"assets.global.backgrounds.spinner-fff-on-2f7bad.js": `+"web/assets/global/backgrounds/spinner-fff-on-2f7bad.`,
	"assets.global.backgrounds.spinner-fff-on-3b94d9.js": `+"web/assets/global/backgrounds/spinner-fff-on-3b94d9.`,
	"assets.global.backgrounds.spinner-fff-on-55acee.js": `+"web/assets/global/backgrounds/spinner-fff-on-55acee.`,
	"assets.global.backgrounds.spinner-fff-on-5e727e.js": `+"web/assets/global/backgrounds/spinner-fff-on-5e727e.`,
	"assets.global.backgrounds.spinner_2b7bb9_on_ccd6dd.js": `+"web/assets/global/backgrounds/spinner_2b7bb9_on_ccd6dd.`,
	"assets.global.backgrounds.spinner_blue.js": `+"web/assets/global/backgrounds/spinner_blue.`,
	"assets.global.backgrounds.spinner_dark.js": `+"web/assets/global/backgrounds/spinner_dark.`,
	"assets.global.backgrounds.spinner_large_dark.js": `+"web/assets/global/backgrounds/spinner_large_dark.`,
	"assets.global.backgrounds.spinner_large_grey.js": `+"web/assets/global/backgrounds/spinner_large_grey.`,
	"assets.global.backgrounds.spinner_large_grey_light.js": `+"web/assets/global/backgrounds/spinner_large_grey_light.`,
	"assets.global.backgrounds.spinner_large_white.js": `+"web/assets/global/backgrounds/spinner_large_white.`,
	"assets.global.backgrounds.spinner_light.js": `+"web/assets/global/backgrounds/spinner_light.`,
	"assets.global.backgrounds.spinner_small_blue_dark_bg.js": `+"web/assets/global/backgrounds/spinner_small_blue_dark_bg.`,
	"assets.global.backgrounds.spinner_small_blue_light_bg.js": `+"web/assets/global/backgrounds/spinner_small_blue_light_bg.`,
	"assets.global.backgrounds.spinner_small_dark.js": `+"web/assets/global/backgrounds/spinner_small_dark.`,
	"assets.global.backgrounds.spinner_small_light.js": `+"web/assets/global/backgrounds/spinner_small_light.`,
	"assets.global.backgrounds.spinner_small_trans.js": `+"web/assets/global/backgrounds/spinner_small_trans.`,
	"assets.global.backgrounds.sprite_sheet_@1x.js": `+"web/assets/global/backgrounds/sprite_sheet_@1x.`,
	"assets.global.backgrounds.sprite_sheet_@2x.js": `+"web/assets/global/backgrounds/sprite_sheet_@2x.`,
	"assets.global.backgrounds.step3_highlight_@1x.js": `+"web/assets/global/backgrounds/step3_highlight_@1x.`,
	"assets.global.backgrounds.step3_highlight_@2x.js": `+"web/assets/global/backgrounds/step3_highlight_@2x.`,
	"assets.global.backgrounds.td_share_collection.js": `+"web/assets/global/backgrounds/td_share_collection.`,
	"assets.global.backgrounds.td_web_dark_dropdown_bg.js": `+"web/assets/global/backgrounds/td_web_dark_dropdown_bg.`,
	"assets.global.backgrounds.td_whatsnew_01.js": `+"web/assets/global/backgrounds/td_whatsnew_01.`,
	"assets.global.backgrounds.td_whatsnew_02.js": `+"web/assets/global/backgrounds/td_whatsnew_02.`,
	"assets.global.backgrounds.td_whatsnew_03.js": `+"web/assets/global/backgrounds/td_whatsnew_03.`,
	"assets.global.backgrounds.td_whatsnew_curate.js": `+"web/assets/global/backgrounds/td_whatsnew_curate.`,
	"assets.global.backgrounds.td_whatsnew_search.js": `+"web/assets/global/backgrounds/td_whatsnew_search.`,
	"assets.global.backgrounds.td_whatsnew_share.js": `+"web/assets/global/backgrounds/td_whatsnew_share.`,
	"assets.global.backgrounds.triangle-15202b.js": `+"web/assets/global/backgrounds/triangle-15202b.`,
	"assets.global.backgrounds.triangle-ffffff.js": `+"web/assets/global/backgrounds/triangle-ffffff.`,
	"assets.global.backgrounds.warning-icon.js": `+"web/assets/global/backgrounds/warning-icon.`,
	"assets.global.backgrounds.web_heart_animation.js": `+"web/assets/global/backgrounds/web_heart_animation.`,
	"assets.global.backgrounds.yellow-highlight.js": `+"web/assets/global/backgrounds/yellow-highlight.`,
	"assets.global.tweetdeck-pride.js": `+"web/assets/global/tweetdeck-pride.`,
	"assets.global.tweetdeck.js": `+"web/assets/global/tweetdeck.`,
	"assets.logos.16.js": `+"web/assets/logos/16.`,
	"assets.logos.48.js": `+"web/assets/logos/48.`,
	"assets.logos.64.js": `+"web/assets/logos/64.`,
	"assets.logos.ios-icon-ipad.js": `+"web/assets/logos/ios-icon-ipad.`,
	"assets.logos.ios-icon-ipad@2x.js": `+"web/assets/logos/ios-icon-ipad@2x.`,
	"assets.logos.ios-icon-iphone.js": `+"web/assets/logos/ios-icon-iphone.`,
	"assets.logos.ios-icon-iphone@2x.js": `+"web/assets/logos/ios-icon-iphone@2x.`,
	"assets.logos.start_logo.js": `+"web/assets/logos/start_logo.`,
	"assets.logos.start_logo@2x.js": `+"web/assets/logos/start_logo@2x.`,
	"assets.sounds.tweet.mp3.js": `***\\+\"web/assets/sounds/tweet\.[a-f0-9]+\.mp3`,
	"assets.sounds.tweet.ogg.js": `***\\+\"web/assets/sounds/tweet\.[a-f0-9]+\.ogg`,
	// "babel-index.3.js": `hasInstance,isConcatSpreadable,iterator,match,replace,search,species,split,toPrimitive,toStringTag,unscopables`,
	"cache.lists.js": `TD.cache.lists=function(`,
	"cache.names.js": `TD.cache.names=((`,
	"components.AccountSelector.js": `TD.components.AccountSelector=a`,
	"components.ActionDialog.js": `TD.components.ActionDialog=TD.components.`,
	"components.AddToListsDialog.js": `TD.components.AddToListsDialog=TD.components.`,
	"components.AddToCustomTimelineDialog.js": `TD.components.AddToCustomTimelineDialog=TD.components.`,
	"components.Autocomplete.js": `TD.components.Autocomplete=TD.components.`,
	"components.BaseModal.js": `TD.components.BaseModal=TD.components.`,
	"components.ConversationDetailView.js": `TD.components.ConversationDetailView=TD.components.`,
	"components.CustomTimelines.js": `TD.components.CustomTimelines=TD.components.`,
	"components.Dataminr.js": `TD.components.Dataminr=TD.components.`,
	"components.DataminrDetailView.js": `TD.components.DataminrDetailView=TD.components.`,
	"components.DetailView.js": `TD.components.DetailView=TD.components.`,
	"components.GlobalSettings.js": `TD.components.GlobalSettings=TD.components.`,
	"components.LiveVideos.js": `TD.components.LiveVideos=TD.components.`,
	"components.InReplyTo.js": `TD.components.InReplyTo=TD.components.`,
	"components.ListMember.js": `TD.components.ListMember=TD.components.`,
	"components.ListMemberList.js": `TD.components.ListMemberList=TD.components.`,
	"components.ListMembers.js": `TD.components.ListMembers=TD.components.`,
	"components.MediaGallery.js": `TD.components.MediaGallery=TD.components.`,
	"components.MenuItem.js": `TD.components.MenuItem=TD.components.`,
	"components.MenuItemBase.js": `TD.components.MenuItemBase=TD.components.`,
	"components.NewFeaturesSplash.js": `TD.components.NewFeaturesSplash=TD.components.`,
	"components.OpenColumn.js": `TD.components.OpenColumn=TD.components.`,
	"components.OpenColumnHome.js": `TD.components.OpenColumnHome=TD.components.`,
	"components.OpenColumnPlaceholder.js": `TD.components.OpenColumnPlaceholder=TD.components.`,
	"components.OpenCustomTimelines.js": `TD.components.OpenCustomTimelines=TD.components.`,
	"components.OpenDataminr.js": `TD.components.OpenDataminr=TD.components.`,
	"components.OpenLiveVideo.js": `TD.components.OpenLiveVideo=TD.components.`,
	"components.OpenSplitMenu.js": `TD.components.OpenSplitMenu=TD.components.`,
	"components.OpenTwitterGeneric.js": `TD.components.OpenTwitterGeneric=TD.components.`,
	"components.ProfileAccount.js": `TD.components.ProfileAccount=TD.components.`,
	"components.RepliesTo.js": `TD.components.RepliesTo=TD.components.`,
	"components.ReplyBar.js": `TD.components.ReplyBar=TD.components.`,
	"components.ScheduledDatePicker.js": `TD.components.ScheduledDatePicker=TD.components.`,
	"components.SearchInput.js": `TD.components.SearchInput=TD.components.`,
	"components.SelfAccounts.js": `TD.components.SelfAccounts=TD.components.`,
	"components.SplitMenu.js": `TD.components.SplitMenu=TD.components.`,
	"components.SuggestedUsers.js": `TD.components.SuggestedUsers=TD.components.`,
	"components.TemporaryColumn.js": `TD.components.TemporaryColumn=TD.components.`,
	"components.TweetDetailView.js": `TD.components.TweetDetailView=TD.components.`,
	"components.TwitterUserSearch.js": `TD.components.TwitterUserSearch=TD.components.`,
	"constants.js": `TD.constants={`,
	"controller.clients.js": `TD.controller.clients=(`,
	"controller.columnManager.js": `TD.controller.columnManager=function(`,
	"controller.feedManager.js": `TD.controller.feedManager=function(`,
	"controller.FeedPoller.js": `TD.controller.FeedPoller=function(`,
	"controller.feedScheduler.js": `TD.controller.feedScheduler=function(`,
	"controller.filterManager.js": `TD.controller.filterManager=(`,
	"controller.notifications.js": `TD.controller.notifications=function(`,
	"controller.scheduler.js": `TD.controller.scheduler=`,
	"controller.upgrade.js": `TD.controller.upgrade=(`,
	"core.base64.js": `TD.core.base64=(`,
	"core.sha1.js": `TD.core.sha1=function(`,
	"decider.js": `TD.config.decider_overlay=(0,r.default)(TD.config.decider_overlay||{}`,
	"flight.js": `/*! Flight v`,
	"globalRenderOptions.js": `TD.globalRenderOptions=(n={`,
	"jquery.js": `Sizzle CSS Selector Engine`,
	"jquery.tools.dateinput.js": `Dateinput - <input type="date" />`,
	"leaflet-src.js": `return!this._container.getElementsByClassName("leaflet-zoom-animated").length`,
	"mapbox.js": `"leaflet-control-mapbox-geocoder leaflet-bar leaflet-control"`,
	"metrics.js": `TD.metrics=function()`,
	"modernizr.prefixed.js": `TRANSITION_END:n({transition:"transitionend",`,
	"moment.js": `&&!e.invalidMonth&&!e.invalidWeekday`,
	"minWrapperVersion.js": `TD.minWrapperVersionMac="`,

	"mustaches.account_selector_avatar": `<img src="{{profileImageURL}}" alt="{{_i}}{{screenName}}'s avatar{{/i}}"`,
	"mustaches.account_settings_account_summary": `<div class="account-summary flex flex-row flex-align--center"> <a href="{{getProfileURL}}" class="js-accordion-toggle-view-prevent txt-size--0 flex" rel="user" target="_blank"> `,
	"mustaches.account_summary": `<div class="account-summary cf"> <a class="obj-left item-img" href="{{getProfileURL}}" data-user-name="{{screenName}}" `,
	"mustaches.account_summary_inline": `<img class="avatar size16 avatar-inline neg-margin-bxs" src="{{profileImageURL}}" alt="{{screenName}}\'s avatar"> @{{screenName}}`,
	"mustaches.action_header": `<h4 class="js-action-header-user-list">{{_i}}From{{/i}}</h4> <div class="js-account-selector-container"></div>`,
	"mustaches.actions.action_dialog": `<div class="mdl-inner mdl-accent padding-h--20 mdl-header-divider"></div> <div class="js-inreply cmp-replyto item-box cf padding-a--20"></div> <div class="cf padding-b--20 padding-r--20 padding-t--5"> <div class="pull-right"> `,
	"mustaches.actions.add_to_customtimeline_dialog": `<section> <form class="frm"> <fieldset> <ul class="control-group padding-bn"> {{#myCustomTimelines}} <li class="margin-b--10"> <label class="checkbox"> <input type="checkbox" name="{{name}}" data-id="{{id}}" data-account="{{#account}}{{getKey}}{{/account}}"/> <span>{{>text/strong}}</span> </label> </li> {{/myCustomTimelines}} </ul> </fieldset> </form> </section>`,
	"mustaches.actions.add_to_list_dialog": `<section> <form class="frm"> <fieldset> <ul class="control-group padding-bs"> {{#myLists}} <li class="margin-b--10"> <label class="checkbox"> <input type="checkbox" name="{{name}}" id="{{id}}" data-account="{{#account}}{{getKey}}{{/account}}"`,
	"mustaches.actions.add_to_list_footer": `<button class="btn js-create-list">{{_i}}Create List{{/i}}</button>`,
	"mustaches.actions.copy_text_modal": `<div class="padding-t--15 padding-h--15 width--490"> <p class="txt-size--13">{{{explanatoryText}}}</p> <div class="flex margin-t--10 margin-b--15"> <input class="js-text-field margin-r--15 min-height--30 flex-auto" name="copy-text" type="text" {{#readonly}}readonly="readonly" {{/readonly}}placeholder="{{placeholderText}}"> {{#showButton}} <button class="js-copy-button Button--primary no-wrap flex-shrink--0" type="button"> {{buttonText}} </button> {{/showButton}} </div> </div>`,
	"mustaches.actions.follow_from": `<div class="js-follow-from l-table padding-al"> <div class="l-cell follow-from-accounts-button margin-r--10"> {{>follow_button}} </div> {{^hideFromAccountName}} <div class="js-from-username l-cell padding-lm follow-from-accounts-username"> {{#account}} <img class="avatar size32 pull-left" src={{getProfileImageURL}} /> <span class="from-handle padding-l--6">from @{{getUsername}}</span> {{/account}} </div> {{/hideFromAccountName}} </div>`,
	"mustaches.add_account_info": `<div class="padding-t--15 txt-center"> <img class="avatar size64" src="{{#asset}}/global/backgrounds/default_profile.png{{/asset}}" alt="Default avatar"> <img class="avatar size30 avatar-border--2`,
	"mustaches.add_column_search_input": `<form action="#" class="search-input-list padding-a--10"> {{> search_input}} </form>`,
	"mustaches.add_image_description": `<div class="width--490"> <img class="width--490" alt="{{_i}}Your uploaded image for description{{/i}}" src="{{src}}"> <div class="flex flex-align--center"> <input type="text" class="js-input-image-description js-input js-submittable-input js-escapable-input height--36 br--6 margin-a--10" maxlength="420" placeholder="{{_i}}Describe this photo for the visually impaired{{/i}}" value="{{initialDescription}}" autofocus data-testid="inputImageDescription"> <span> <button class="js-submit-image-description Button--primary margin-a--10 {{^canSubmit}}is-disabled{{/canSubmit}}"`,
	"mustaches.app_container": `<div class="js-progress-indicator"></div> <div class="js-app-content app-content"> {{>drawer}} <div class="js-app-columns-container app-columns-container scroll-h needs-scroll-bottom-offset {{#styledScrollbar}}scroll-styled-h{{/styledScrollbar}}" id="container"> `,
	"mustaches.app_links": `<a href="https://www.twitter.com/tos" target="_blank">{{_i}}Terms of Service{{/i}}</a> <span class="aria-hidden">&middot;</span> <a href="https://twitter.com/privacy" target="_blank">{{_i}}Privacy Policy{{/i}}</a> <span class="aria-hidden">&middot;</span>`,
	"mustaches.buttons.favorite": `<div class="js-btn-fav js-show-tip pull-left btn-fav margin-r--5" data-account-key="{{getKey}}"> <button class="btn-loader"> <span> <img src="{{#asset}}/global/backgrounds/spinner_small_trans.gif{{/asset}}" alt="{{_i}}Loading…{{/i}}"> </span> </button> <button class="btn-fav-fav-text Button--tertiary btn-on-dark"> <i class="icon icon-favorite icon-favorite-color"></i> <span class="label">{{_i}}Like{{/i}}</span> </button> <button class="btn-fav-faved-text Button--primary"> <span class="label">{{_i}}Liked{{/i}}</span> </button> <button class="btn-fav-unfav-text btn-on-dark">`,
	"mustaches.buttons.load_more": `<input type="button" name="remove-account" value="Load more" class="js-load-more small btn btn-alt margin-vl obj-center">`,
	"mustaches.chart_with_controls": `<div class="flex flex-justify-content--space-between flex-align--center margin-b--20"> <h1 class="txt-size--16 txt-bold max-width-p--60">{{title}}</h1> <div class="js-insights-date-picker"></div> </div> <div class="js-chart-terms margin-b--20"></div> <div class="js-insights-grid-chart"></div>`,
	"mustaches.column": `<div class="js-column-holder column-holder"> <div class="column-panel flex flex-column height-p--100"> {{> column/column_header}} {{#isSearch}} <div class="js-search-filter-callout"></div> {{/isSearch}} <div class="js-column-content column-content flex-auto position-rel flex flex-column height-p--100"> <div class="js-column-options-container column-options flex-shrink--0 z-index--2"> <div class="js-column-options {{#isTouchColumnOptions}}with-touch-txt-base{{/isTouchColumnOptions}}"></div>`,
	"mustaches.column.add_to_custom_timeline": `<div class="InputGroup margin-t--8"> <input class="js-add-to-customtimeline-input js-submittable-input" type="text" placeholder="{{_i}}Enter Tweet URL{{/i}}" value="" data-account-key="{{accountKey}}" data-customtimeline-id="{{customTimelineId}}" > <button class="js-add-to-customtimeline-button js-spinner-button btn-round"> <i class="icon icon-arrow-r"></i> <i class="js-spinner-button-active icon spinner-small-trans icon-center-16 is-hidden"></i> </button> </div>`,
	"mustaches.column.add_to_customtimeline_drop_indicator": `<div id="{{dropIndicatorIdName}}" class="{{dropIndicatorClassName}} drag-drop-indicator`,
	"mustaches.column.add_to_customtimeline_drop_indicator_spinner": `<div class="spinner-small spinner-small-blue-bg spinner-centered-auto"></div>`,
	"mustaches.column.chirp_container": `<div class="js-column-scroller js-dropdown-container column-scroller position-rel scroll-v flex-auto height-p--100 {{#styledScrollbar}}scroll-styled-v{{/styledScrollbar}} {{#isTemporary}}column-background-fill scroll-alt{{/isTemporary}}"> <div class="js-chirp-container chirp-container" data-column="{{columnkey}}"> {{>column_loading_placeholder}} </div> </div>`,
	"mustaches.column.column_dm_participants": `{{> column/column_header_detail}} <div class="js-conversation-adder add-participant`,
	"mustaches.column.column_filter_error": `data-action="action-filter"> {{_i}}Filter error{{/i}} </p>`,
	"mustaches.column.column_header": `<header class="js-column-header js-action-header flex-shrink--0 {{^isTemporary}}column-header{{/isTemporary}} {{#isTemporary}}column-header-temp{{/isTemporary}}" data-action="resetToTopColumn"> {{^isTemporary}} <i class="js-column-drag-handle is-movable column-drag-handle pull-left sprite sprite-drag-vertical"></i> `,
	"mustaches.column.column_header_detail": `<header class="{{headerClass}} visible-overflow--important column-header flex flex-justify-content--space-between padding-h--10" data-action="{{headerAction}}"> <a class="{{headerLinkClass}} link-complex flex-auto" href="#"> {{^getConversationTitleInformation}} <div class="column-title-back txt-ellipsis"> <i class="icon icon-arrow-l"></i>`,
	"mustaches.column.column_options": `<form data-testid="columnOptions" class="with-column-divider-bottom"> `,
	// "mustaches.column.column_options_header": `This mustache has nothing in it, so idk what to do`,
	"mustaches.column.custom_timeline_description": `{{#description}} {{#editable}} <button class="js-edit pull-right padding-a--0 width--30 Button--link margin-txs"> <i class="icon icon-edit txt-mute txt-size--14 padding-txs"></i> </button> {{/editable}} `,
	"mustaches.column.dm_rename_conversation": `<div class="js-edit-conversation-name edit-conversation-name cf" data-conversation-id="{{conversationId}}" data-account-key="{{accountKey}}" > <div class="obj-right"> <button class="btn-round bg-color-transparent" data-action="confirm-edit-conversation">`,
	"mustaches.column.filter_callout": `<div data-testid="filterCallout"> <div class="search-filter-callout-triangle pin-right margin-r--13 margin-t---14"></div>`,
	"mustaches.column.preferences": `<div class="js-accordion-item facet-type facet-type-preferences"> {{>menus/accordion_header}} `,
	"mustaches.column.trend_select_item": `<option value="{{value}}" {{#isSelected}}selected{{/isSelected}}>{{title}}</option>`,
	"mustaches.column.trends_options": `<div class="padding-a--8"> <div class="position-rel"> <label for="select-trend-for" class="vertical-center pull-left txt-mute">Trends for</label> <select name="select-trend-for" class="js-trend-select trend-select"> </select> </div> <div class="js-city-select-panel position-rel margin-t--5 "> <label for="select-trend-for" class="vertical-center pull-left txt-mute">City</label> <select name="select-trend-for" class="js-cities-select trend-select"> </select> </div> </div>`,
	"mustaches.column_loading_placeholder": `<div data-testid="columnLoadingPlaceholder" class="js-column-loading-placeholder list-placeholder column-loading-placeholder"> <p><span class="spinner-small"></span> {{^isUpdating}}`,
	"mustaches.column_nav_flyout": `<div class="js-column-nav-menu-flyover column-nav-flyout"> `,
	"mustaches.column_title": `<span class="column-heading">{{{emojifiedTitle}}}</span> {{#needsUserAttribution}} <span class="attribution txt-mute`,
	"mustaches.column_title_editable": `<input type="text" class="js-submittable-input js-column-title-edit-box column-title-edit-box Button--large txt-size--14 {{editableFieldClass}}" maxlength="{{maxLength}}" value="{{title}}">`,
	"mustaches.command_palette.base": `<div class="width--490 max-height--400 padding-a--10 br--6 bg-color-twitter-lightest-gray flex flex-column"> <input type="text" `,
	"mustaches.command_palette.command_list": `<ul> {{#commands}} <li class="js-command {{classes}} padding-a--8 br--6 is-actionable txt-size--13 txt-line-height--13" data-index="{{index}}"> <div class="flex flex-row"> `,
	"mustaches.compose.account_selector": `<div class="margin-b--11 compose-accounts flex flex-wrap--wrap {{gridModeClass}}"> {{#accounts}} <a class="js-account-item {{^isListGridMode}}js-show-tip{{/isListGridMode}} `,
	"mustaches.compose.account_selector_grid_toggle": `<a class="pull-left margin-r--6 is-actionable account-selector-grid-mode {{#grid}}is-selected{{/grid}}" data-grid-mode="grid"><i class="color-twitter-white icon icon-compose-grid">`,
	"mustaches.compose.accounts": `{{#accounts}} <a class="js-account-item js-show-tip compose-account is-actionable link-clean" tabindex="0" title="@{{screenName}}" data-account-key="{{accountKey}}" `,
	"mustaches.compose.autocomplete_hashtag": `{{#results}} <li class="typeahead-item padding-am cf is-actionable"> <p class="js-hashtag txt-ellipsis">{{{value}}}{{>text/hashflag}}</p> </li> {{/results}}`,
	"mustaches.compose.autocomplete_twitter_user": `{{#results}} <li class="typeahead-item padding-am cf is-actionable" data-id="{{id}}"> <img src="{{pic}}" class="avatar obj-left size24"> <div class="nbfc txt-ellipsis padding-ts"> <strong class="fullname">`,
	"mustaches.compose.character_count_with_circle": `<div class="txt-right height--16 margin-t--4 {{#inline}}margin-r--7 margin-b--11{{/inline}} {{^inline}}margin-r---3 margin-b--1{{/inline}}"> <span class="js-character-count `,
	"mustaches.compose.close_button": `<i class="icon icon-close color-twitter-white bg-color-twitter-deep-black txt-size--16 padding-a--3 br-100 opacity--70 opacity-hover--100 lh--14"></i>`,
	"mustaches.compose.compose_inline_reply": `<div class="js-inline-reply inline-reply item-box-full-bleed is-inline-inactive is-inline-active position-rel"> <div class="padding-t--10 padding-lxl padding-rxl padding-b--10"> <div class="position-rel compose-text-container margin-v--6 br--4"> `,
	"mustaches.compose.custom_video_controls": `<div class="video-controls br--4 full-width padding-a--5 pin-bottom border-box"> <progress class="js-video-progress opacity--80 opacity-hover--100 ProgressBar ProgressBar--white width-p--95" role="progressbar" value="0" max="1" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1"></progress>`,
	"mustaches.compose.docked_compose": `<div class="js-docked-compose compose txt-size--14"> <div class="js-compose-scroller compose-content antiscroll-wrap pin-all"> <div class="antiscroll-inner scroll-v scroll-styled-v padding-h--15"> <header class="js-compose-header compose-header"> <div class="position-rel compose-title inline-block"> <h1 class="js-compose-title compose-title-text txt-ellipsis inline-block">{{_i}}New Tweet{{/i}}</h1> </div> <i class="js-compose-close is-actionable icon icon-close margin-v--20 pull-right{{#rwebComposerEnabled}}`,
	"mustaches.compose.image_description_field": `<div class="js-add-image-description color-twitter-white bg-color-twitter-deep-black {{#isMediaGridContent}}padding-a--4 pin-left pin-bottom txt-size--11{{/isMediaGridContent}}{{^isMediaGridContent}}txt-size--12 padding-a--10 pin-left--15 pin-bottom--17{{/isMediaGridContent}} br--14 opacity--70 opacity-hover--100 is-actionable margin-t---20 z-index--1 txt-ellipsis max-width-p--70"> {{#description}}{{description}}{{/description}}{{^description}}{{_i}}Add description{{/i}}{{/description}} </div>`,
	"mustaches.compose.in_reply_to": `{{#user}} <header class="tweet-header padding-bm position-rel"> <a href="#" class="js-in-reply-to-remove pull-right compose-reply-tweet-remove margin-axs"><i class="icon icon-close"></i></a> <a class="account-link link-complex block txt-ellipsis margin-r--10" href="https://twitter.com/{{screenName}}" rel="user" target="_blank"> <img class="compose-reply-avatar avatar size24" src="{{profileImageURL}}" width="24" height="24"> <b class="fullname link-complex-target">{{name}}</b> {{#isVerified}}`,
	"mustaches.compose.media_bar_image": `{{#isMediaGridContent}} <div class="compose-media-grid-holder bg-color-twitter-white padding-am margin-t---4"> <div class="media-grid-container"> <div class="media-grid-{{mediaLength}}"> {{#mediaInfo}} <div class="media-image-container block position-rel"> <div class="pin-all media-image br--4" style="background-image: url({{src}});" > <a class="js-media-bar-remove compose-media-grid-remove is-actionable" data-file-index="{{fileIndex}}"> {{>compose/close_button}}`,
	"mustaches.compose.media_bar_infobar": `<div class="compose-media-info-bar-holder padding-al"> <div class="compose-media-info-bar cf padding-as"> <div class="obj-left"> <i class="icon icon-camera align-middle"></i> <span class="align-middle">{{_i}}Image added{{/i}}</span> </div> <div class="obj-right"> <a href="#" class="js-media-bar-remove align-middle">{{_i}}Remove{{/i}}</a> </div> </div> </div>`,
	"mustaches.compose.message_conversation": `{{#chirp}} <div class="js-compose-message-recipient compose-message-recipient margin-t--4 margin-l--4 color-twitter-darker-gray flex flex-row flex-align--center max-full-width br--14" data-conversation-id="{{conversationId}}"> {{^withMultipleAvatars}} {{#avatars.0}} <img class="flex-shrink--0 margin-a--1 br-100" src="{{profileImageURL}}" width="24" height="24" alt="{{screenName}}\'s avatar"> {{/avatars.0}} {{/withMultipleAvatars}} {{#withMultipleAvatars}} <div class="flex-shrink--0 margin-a--1 media-grid-container multiple-avatar-grid-mini "> <div class="{{avatarsClass}}"> `,
	"mustaches.compose.message_recipients": `{{#users}} <div class="js-compose-message-recipient compose-message-recipient margin-t--4 color-twitter-darker-gray flex flex-row flex-align--center max-full-width br--14 border-box" data-user-id="{{id}}" data-screen-name="{{screenName}}"> <img class="flex-shrink--0 padding-a--1 br-100" src="{{profileImageURL}}" width="24" height="24" /> <span class="flex-shrink--1 txt-ellipsis margin-l--4">{{name}}</span> <a class="js-remove-recipient is-actionable txt-mute`,
	"mustaches.compose.reply_info": `{{_i}} <div class="other-replies txt-ellipsis"> Replying {{#recipients}} to <a href="#" class="js-other-replies-link`,
	"mustaches.compose.reply_list": `<ul class="lst"> <li class="padding-axl"> <p class="txt-size--14 color-twitter-dark-gray"> {{#withComposeContext}} {{_i}}Your Tweet will go to the people in this conversation.{{/i}} {{/withComposeContext}} {{^withComposeContext}} {{_i}}This conversation includes these people.{{/i}} {{/withComposeContext}} </p> </li> {{#replies}} <li class="padding-axl flex flex-row flex-align--center"> <div class="flex-auto margin-rxl">{{> account_summary}}</div> {{#withComposeContext}}`,
	"mustaches.compose.schedule": `<div class="popover popover-position-t bg-color-twitter-white margin-ll padding-a--3" style="display:block"> <div class="caret"> <span class="caret-outer"></span> <span class="caret-inner"></span> </div> <div class="cal"> <header> <input id="scheduled-hour" type="text" pattern="\\d*" inputmode="numeric" tabindex="2" class="light-on-dark"> <span>:</span> `,

	"mustaches.contributor_list_account_summary": `<div class="account-summary cf flex"> <div class="obj-left item-img flex-align-self--center"> <img class="avatar size36 avatar pull-right" src="{{profileImageURL}}" width="36" height="36" alt="{{screenName}}\'s avatar"> </div> <div class="account-summary-text nbfc account-link"> <span class="account-inline txt-ellipsis {{#isProtected}}is-protected{{/isProtected}}">`,
	"mustaches.contributors.contributor_list": `{{#contributors}} {{>contributors/contributor_list_row}} {{/contributors}}`,
	"mustaches.contributors.contributor_list_error": `<div class="padding-axl margin-tl color-twitter-red"> {{_i}}Could not retrieve team members.{{/i}}`,
	"mustaches.contributors.contributor_list_row": `{{#contributor}} <div class="js-contributor-row contributor-row position-rel padding-axl account-settings-bb" data-state="{{initialState}}" data-state-error data-user-id="{{user.id}}" data-name="{{user.name}}" data-contributor-role="{{#isAdmin}}admin{{/isAdmin}}{{^isAdmin}}contributor{{/isAdmin}}"> {{#user}} {{>contributor_list_account_summary}} {{/user}} <div class="contributor-settings control-s margin-txl cf" data-show-when-state="settings`,
	"mustaches.contributors.contributor_manager": `<div class="drawer-header padding-lxl flex-shrink--0"> <h1 class="js-contributor-manager-back is-actionable pull-left txt-weight-normal"> <span class="drawer-header-title block drawer-column-header-title"> `,
	"mustaches.contributors.contributors_loading": `<div class="padding-hxl"> {{_i}}Loading team...{{/i}} </div>`,
	"mustaches.customtimeline.edit_customtimeline": `<div class="customtimeline-details margin-b--15 padding-t--25 padding-h--15 width--490"> <fieldset> <div class="control-group padding-b--15"> <label for="customtimeline-account" class="control-label">{{_i}}Account{{/i}}</label> <div class="controls"> <select{{#timelineId}}`,
	"mustaches.data_drawer": `<div class="js-drawer-body"> <div class="js-insights-panel"> </div> </div> <div class="js-drawer-footer"> <button class="js-drawer-action Button--primary pull-right">Tweet {{insightTerm}}</button> </div>`,
	"mustaches.drawer": `<div class="js-drawer drawer" data-drawer="compose"> </div> <div class="js-drawer drawer" data-drawer="accountSettings"> </div>`,
	"mustaches.embed_tweet": `<div> {{$content}} <div class="margin-h--15 margin-b--20"> <span class="block margin-bl">{{_i}}Add this Tweet to your website by copying the code below. If your CMS supports it, you can just paste in the link.{{/i}} <a class="url" target="_blank"`,
	"mustaches.favorite_from_options": `{{#accounts}} <div class="l-table padding-al"> <div class="l-cell"> {{>buttons/favorite}} <div class="inline-block"> <img class="avatar size32 pull-left" src={{getProfileImageURL}} /> <span class="from-handle padding-l--6">@{{getUsername}}</span> </div> </div> </div> `,
	"mustaches.feather-component-card-video": `<div class="Card-video"> {{#cardUsePublishedVideo}} <iframe class="Card-videoIframe" src="https://twitter.com/i/videos/{{tweetId}}?square_corners=1"></iframe> {{/cardUsePublishedVideo}} `,
	"mustaches.follow_button": `<div class="js-action-follow btn-relation-group"> <div class="js-follow-button pull-left {{^isSingleAccount}}js-show-tip{{/isSingleAccount}} follow-btn margin-r--4{{^showAccountMenu}} `,
	"mustaches.heartsprite": `<i class="heartsprite heart-anim"></i>`,
	"mustaches.important_update": `<div data-testid="gdprImportantUpdateModal" class="txt-center padding-v--30 padding-h--50 width--523"> <i class="padding-v--30 icon icon-twitter-bird color-twitter-blue txt-size--30"></i> <h1 class="padding-v--20 txt-size--22 txt-bold">{{_i}}Updates to the Twitter Terms of Service and Privacy Policy{{/i}}</h1> `,
	"mustaches.inline_confirmation": `<div class="inline-confirmation-container padding-axl {{backgroundColorClass}} br--4"> <div class="inline-confirmation-text {{textColorClass}}"> {{confirmationText}} </div> <div class="margin-txl cf"> `,
	"mustaches.insights.demographics": `<div class="margin-v--26"> <h4 class="txt-size--16 txt-bold margin-b--8">{{title}}</h4> <div class="txt-right txt-size--12">{{_i}}% of audience{{/i}}</div> <ol class="border-separated"> {{#ageInsights}} <li class="flex txt-size--14 margin-t--4 padding-v--20"> <div class="width-p--5"> {{ordinal}} </div> <div class="width-p--50"> {{name}} </div> <div class="width-p--45 flex"> <div class="width-5 margin-h--10 txt-right">{{percentage}}%</div> `,
	"mustaches.insights.insights_panel": `<div class="color-twitter-black"> <div class="js-insights-main-chart"></div> <div class="js-no-data"></div> <div class="js-top-related"></div> <div class="js-demographics"> <div class="js-demographics-age"></div> </div> </div>`,
	"mustaches.insights.no_data": `<div class="txt-center color-twitter-dark-gray margin-t--50"> <p class="txt-size--18 padding-b--8">{{_i}}Nothing to see here &mdash; yet{{/i}}</p>`,
	"mustaches.insights.related_words": `<div class="margin-v--26"> <h4 class="txt-size--16 txt-bold margin-b--8">{{_i}}Related terms{{/i}}</h4> <ol class="border-separated"> {{#rows}} <li class="flex flex-align--center txt-size--14 margin-t--4 padding-v--15"> <div class="width-p--5"> {{ordinal}} </div> <div class="width-p--50"> `,
	"mustaches.item_box": `<div class="item-box {{$item_box_classes}}{{/item_box_classes}}" {{$item_box_data}}{{/item_box_data}}> {{$content}}{{/content}} </div>`,
	"mustaches.keyboard_shortcut_list": `<div> {{$content}} <dl class="keyboard-shortcut-list mdl-column"> <dt class="keyboard-shortcut-title"><b>Actions</b></dt> <dd class="keyboard-shortcut-definition"><kbd class="text-like-keyboard-key">R</kbd>  Reply</dd> <dd class="keyboard-shortcut-definition"><kbd class="text-like-keyboard-key">T</kbd>  Retweet</dd> <dd class="keyboard-shortcut-definition"><kbd class="text-like-keyboard-key">F</kbd> {{_i}}Like{{/i}} </dd> <dd class="keyboard-shortcut-definition"><kbd class="text-like-keyboard-key">N</kbd> `,
	"mustaches.large_modal": `<div class="js-modal-panel mdl s-tall-fixed"> {{> modal_header}} <div class="mdl-inner"> <div class="mdl-content js-mdl-content horizontal-flow-container"> </div> <footer class="mdl-buttonbar">`,
	"mustaches.learn_more_about_reporting": `<p class="padding-axl color-twitter-deep-black">{{_i}} <a href="https://support.twitter.com/articles/15794-online-abuse" target="_blank" rel="url">Learn more</a> `,
	"mustaches.list_module_account_item": `<li> <a href="#" class="list-account s-justify cf"> <img src="{{profileImageURL}}" alt="@{{username}}" class="avatar obj-left"> <div class="nbfc"> <strong class="fullname"> {{{emojifiedName}}}`,
	"mustaches.list_module_dataminr_watchlist": `<li> <a href="#" class="list-twitter-list" data-id="{{id}}"> <div class="inner" > <strong>{{name}}</strong> </div> <p>{{description}}</p> </a> </li>`,
	"mustaches.list_module_events": `<div class="lst-group"> <ul class="js-events-list"></ul> </div>`,
	"mustaches.list_module_list_item": `<li class="{{#selected}}selected{{/selected}} {{classes}}"><a href="#" class="list-link" data-action="{{action}}"><strong>{{title}}</strong><i class="chev-right"></i></a></li>`,
	"mustaches.list_module_livevideos": `<div class="lst-group"> <ul class="js-live-videos-list"></ul> </div>`,
	"mustaches.list_module_subtitle_item": `<li><a href="#" class="list-subtitle">{{title}}<span>{{subtitle}}</span><i class="chev-right"></i></a></li>`,
	"mustaches.list_module_trend_header": `<header class="margin-am"> <div class="js-trends control-group is-hidden"> <label class="padding-ts pull-left txt-mute cont">{{_i}}Trends{{/i}}</label> <div class="controls-space-58"> <select class="js-trends-select"></select> </div> </div> <div class="js-cities control-group is-hidden margin-ts"> <label class="padding-ts pull-left txt-mute cont">{{_i}}City{{/i}}</label> <div class="controls-space-58"> <select class="js-cities-select"></select> </div> </div> </header>`,
	"mustaches.list_module_trends": `<div class="lst-group"> {{^withLocationSelector}} <h3>{{_i}}Worldwide{{/i}}</h3> {{/withLocationSelector}} {{> list_module_trend_header}} <ul class="js-trend-list"></ul> </div>`,
	"mustaches.list_module_twitter_customtimeline_item": `<li> <a href="#" class="list-twitter-list"> <div class="inner" > <strong>{{{title}}}</strong> </div> <p>{{{description}}}</p> </a> </li>`,
	"mustaches.list_module_twitter_list_item": `<li> <a href="#" class="list-twitter-list"> <div class="inner"> <div class="txt-ellipsis"> {{#isPrivate}}<i class="icon icon-protected icon-small inline"></i>{{/isPrivate}} <strong>{{{title}}}</strong> <span class="bytext">{{by}}</span> </div> </div> <p class="txt-ellipsis">{{{description}}}</p> <span class="subtitle">{{subtitle}}</span> <img src="{{miniProfileURL}}" alt="avatar" class="avatar size24"> </a> </li>`,
	"mustaches.list_option_dropdown": `<span class="btn-dropdown-group"> <a href="#" class="btn-dropdown"> <span class="js-menu-selected-item">{{choice}}</span> <i class="carrot-down"></i> </a> <ul class="options-dropdown dropdown-menu" style="display:block"> <li><a href="#">{{_i}}Ping{{/i}}</a></li>`,
	"mustaches.list_trend_item": `<li><a href="#" data-action="search" data-query="{{name}}">{{name}}</a></li>`,
	"mustaches.list_trend_promoted_item": `<li><a class="promoted" href="#" data-action="search" data-query="{{name}}">{{name}}<i class="badge-promoted"></i><span>promoted</span></a></li>`,
	"mustaches.lists.add_users_to_list_button": `<button class="js-add-multiple Button--primary margin-t--10" {{^canAddMembers}}disabled{{/canAddMembers}}> `,
	"mustaches.lists.edit_footer": `<span class="pull-right"> <button class="js-save Button--primary"><i class="add"></i>{{_i}}Save{{/i}}</button> </span>`,
	"mustaches.lists.edit_list_details": `<div class="margin-b--15 padding-t--25 padding-h--15 width--490"> <fieldset> <legend class="frm-legend">{{_i}}List Details{{/i}}</legend> <div class="control-group padding-b--15"> <label for="list-account" class="control-label">{{_i}}Account{{/i}}</label> <div class="controls"> <select{{#listId}} disabled{{/listId}}`,
	"mustaches.lists.edit_members_footer": `<button class="js-delete Button--danger"> <span class="label">{{_i}}Delete List{{/i}}</span> </button> <span class="pull-right"> <label class="js-add-column-option is-hidden pull-left checkbox frm-add-col"> <input type="checkbox" class="js-add-column-checkbox" name="add-column-checkbox"/> <span>{{_i}}Add column{{/i}}</span> </label> <button class="js-edit btn Button--tertiary btn-on-dark margin-r--6">{{_i}}Edit details{{/i}}</button> <button class="js-done Button--primary"></i>{{_i}}Done{{/i}}</button> </span>`,
	"mustaches.lists.member": `<li class="list-listmember cf"> <img src="{{profileImageURL}}" alt="@{{username}}" class="avatar"> <button class="js-add-remove btn btn-on-dark btn-round Button--tertiary"> <div class="working action-btn"> <span> <img src="{{#asset}}/global/backgrounds/spinner_small_trans.gif{{/asset}}" alt="{{_i}}Loading…{{/i}}"> </span> </div> <div class="member action-btn"><i class="icon icon-trash"></i></div> <div class="checked action-btn"><i class="icon icon-check icon-small"></i></div>`,
	"mustaches.lists.member_export": `<div class="lst-group"> <div class="margin-a--16"> <p class="padding-b--8 color-twitter-dark-gray">{{_i}}These are the accounts in {{/i}}{{{name}}}{{_i}}. You can copy them to share.{{/i}}</p> <textarea class="height--415 js-copy-users-input" readonly>{{members}}</textarea> <div> <button class="js-dismiss-top-modal btn margin-t--10 pull-left btn-on-dark"> {{_i}}← Back{{/i}} </button> {{#showCopyButton}} <div class="pull-right"> <button class="js-copy-members Button--primary margin-t--10"> {{_i}}Copy List{{/i}}`,
	"mustaches.lists.member_import": `<div class="lst-group"> <div class="margin-a--16 color-twitter-dark-gray"> <p class="padding-b--8">{{_i}}Enter the @usernames of the people you would like to add to this List.{{/i}}</p> <p class="padding-b--16 txt-size-variable--12 pull-left width-p--90">{{_i}}You can add up to 100 members to a List at a time.{{/i}}</p> <i class="js-show-tip icon icon-info pull-right" data-title="{{_i}}You can add the @usernames one per line, or they can be separated by spaces, commas or tabs.{{/i}}"/>`,
	"mustaches.lists.member_list": `<section id="{{columnkey}}" data-column="{{columnkey}}" class="flex flex-column height-p--100"> <header class="column-header column-header-temp flex-shrink--0"> <h1 class="pull-left padding-h--10"><strong>{{_i}}Members{{/i}}</strong> (<span class="js-member-count"></span>)</h1> <button class="js-action-header-export-button pull-right btn Button--tertiary btn-on-dark margin-t--10 is-hidden" data-action="exportList">{{_i}}Export List{{/i}}</button> </header> <div class="scroll-v {{#styledScrollbar}}`,
	"mustaches.live_video": `<div class="js-live-video-container live-video-container position-rel"></div> {{^isTemporaryColumn}} {{#hasMultipleTimelines}} <div class="live-video-timelines height--30 {{^decider.live_video_timelines}}is-hidden{{/decider.live_video_timelines}}"> <button class="Button Button--small js-live-video-timelines"> <span class="Button-label js-live-video-timelines-label">{{primaryTimeline.title}}</span> <span class="Button-adornment"> <span class="Icon Icon--caretDown"></span> </span> </button>`,
	"mustaches.login.login_form": `<div class="app-signin-wrap"> {{> login/promo_for_login_form}}`,
	"mustaches.login.login_form_message": `<div class="js-login-error form-message form-error-message error txt-center padding-al margin-bxl {{^message}}is-hidden{{/message}}"> <p class="js-login-error-message">`,
	"mustaches.login.promo_for_login_form": `<div class="app-info txt-size-variable--18 margin-txxl"> <div class="app-info-panel cf"> `,
	"mustaches.login.twitter_account_login_form": `<section class="js-login-form form-login startflow-panel-rounded" data-auth-type="twitter" aria-labelledby="login-form-title"> <h2 class="form-legend padding-axl" id="login-form-title"> `,
	"mustaches.media.animated_gif": `<div class="js-media-gif-container media-item nbfc {{thumbSizeClass}}" style="background-image: url({{imageSrc}})"> {{#isGifActive}} `,
	"mustaches.media.media_gallery": `<div class="js-mediatable ovl-block is-inverted-light" tabindex="-1"> <div class="s-padded"> <div class="js-modal-panel mdl s-full med-fullpanel">`,
	"mustaches.media.media_upload": `<input class="js-media-upload" type="file" accept="{{acceptedMedia}}" multiple />`,
	"mustaches.media.native_video": `<div class="position-rel"> <iframe src="https://twitter.com/i/videos/{{#isDM}}dm{{/isDM}}{{^isDM}}tweet{{/isDM}}/{{chirpId}}?image_src={{imageSrc}}&amp;`,
	"mustaches.media.scheduled_video": `<div class="js-scheduled-video"></div>`,
	"mustaches.media.tagged_users": `{{#taggedUsers.length}} <div class="margin-v--4 txt-mute txt-size-variable--12"> <i class="icon icon-user icon-xsmall icon-base-valigned "></i> {{#taggedUsers}} `,
	"mustaches.media.video_overlay": `<div class="video-overlay icon-with-bg-round">`,
	"mustaches.media.vine": `}" src="https://vine.co/v/{{id}}/card" `,
	"mustaches.media.youtube": ` src="https://www.youtube.com/embed/{{id}}?autoplay={{autoplay}}{{#startTime}}&start={{startTime}}{{/startTime}}" allowfullscreen frameborder="0"> </iframe>`,

	"mustaches.menus.accordion_header": `<div class="js-accordion-toggle-view accordion-header is-actionable link-clean block cf txt-size--14"> `,
	"mustaches.menus.actions": `<ul> {{#chirp}} {{#user}}{{^isProtected}} <li class="is-selectable"><a href="#" data-action="embed">{{_i}}Embed this Tweet{{/i}}</a></li> <li class="is-selectable"><a href="#" data-action="reference-to">{{_i}}Copy link to this Tweet{{/i}}</a></li> <li class="is-selectable"><a href="#" data-action="message-to">{{_i}}Share via Direct Message{{/i}}</a></li> <li class="is-selectable"><a href="#" data-action="email">{{_i}}Share via Email{{/i}}</a></li> <li class="drp-h-divider"></li> {{/isProtected}}`,
	"mustaches.menus.actions_directmessage": `<ul> {{#user}} {{> menus/follow_menuitem }} <li class="is-selectable"><a href="#" data-action="lists">{{_i}}Add or remove from Lists…{{/i}}</a></li> {{^isMe}} <li class="drp-h-divider"></li> {{^isMuted}} <li class="is-selectable"><a href="#" data-action="mute">{{_i}}Mute @{{screenName}}{{/i}}</a></li> {{/isMuted}} {{#isMuted}} <li class="is-selectable"><a href="#" data-action="unmute">{{_i}}Unmute @{{screenName}}{{/i}}</a></li> {{/isMuted}} <li class="is-selectable"><a href="#"`,
	"mustaches.menus.column_nav_menu": `<div class="js-column-nav-list"> <ul class="js-int-scroller"> {{#columns}} <li class="js-column-nav-menu-item column-nav-item {{#isNew}}is-new{{/isNew}} {{#customTimelineId}}js-droptarget{{/customTimelineId}}" data-column="{{key}}" data-customtimeline-id="{{customTimelineId}}" data-customtimeline-account="{{customTimelineAccount}}" > <i class="icon icon-xsmall icon-dot column-nav-updates"></i> <a class="js-header-action js-drag-handle drag-handle link-clean cf`,
	"mustaches.menus.column_share": `<ul class="dropdown-text-large"> {{#isEmbeddable}} <li class="is-selectable"> <a href="#" data-action="embed"> <i class="icon icon-dropdown-context icon-share margin-rs"></i> {{_i}} {{>text/open_strong}}Embed{{>text/close_strong}} {{#isCustomTimeline}} Collection {{/isCustomTimeline}} {{^isCustomTimeline}} timeline {{/isCustomTimeline}} {{/i}} </a> </li> {{/isEmbeddable}} {{#isSearchColumn}} <li class="is-selectable"> <a href="#" data-action="copy-search-query">`,
	"mustaches.menus.datetime_footer": `<div> <button type="button" class="btn Button--tertiary js-clear-date">Clear</button> </div>`,
	"mustaches.menus.datetime_input": `<div class="search-input-control"> <input type="text" class="js-datetime-input txt-left width-p--100" placeholder="{{placeHolderText}}" readonly /> `,
	"mustaches.menus.dm_conversations_menu": `<ul> <li class="is-selectable"><a href="#" data-action="view-people">{{_i}}Add / view people{{/i}}</a></li> {{#group}} <li class="is-select`,
	"mustaches.menus.dropdown": `<div class="js-dropdown dropdown-menu br--6 padding-v--9 {{position}}"> <div class="caret"> <span class="caret-outer"></span> <span class="caret-inner"></span> </div> <div class="js-dropdown-content"> </div> </div>`,
	"mustaches.menus.filter_info_generic": `<div class="txt-size--11 padding-b--10 flex flex-row"> <div class="flex-shrink--0 margin-r--6"> <i class="icon icon-info icon-small"/> </div> <div> {{_i}} Your notification settings on <a rel="url noopener noreferrer" target="_blank"`,
	// "mustaches.menus.flagged_media": `Uhhhhhh there's nothing here idk what to do`,
	"mustaches.menus.follow_menuitem": `{{#isSingleAccount}} {{^isMe}} {{#following}} <li class="is-selectable"><a href="#" data-action="unfollow" class="txt-ellipsis">{{_i}}Unfollow @{{screenName}}{{/i}}</a></li> {{/following}} {{^following}} <li class="is-selectable"><a href="#" data-action="follow" class="txt-ellipsis">{{_i}}Follow @{{screenName}}{{/i}}</a></li> {{/following}} {{/isMe}} {{/isSingleAccount}} {{^isSingleAccount}} <li class="is-selectable"><a href="#" data-action="followOrUnfollow">`,
	"mustaches.menus.notifications_info": `{{#filters.length}} <div class="txt-size--13 padding-b--5"> <div class="txt-bold padding-b--3">{{_i}}Hiding notifications from users:{{/i}}</div> <ul> {{#filters}} <li class="padding-b--3"> <i class="icon icon-check notifications-info-icon"/> {{text}} </li> {{/filters}} </ul> </div> <div class="txt-size--11 padding-b--12"> {{_i}}These filters will not affect notifications from people you follow.{{/i}} <a rel="url noopener noreferrer" target="_blank" href="https://twitter.com/settings/notifications_timeline">`,
	"mustaches.menus.quality_filter_info": `<div class="txt-size--11 padding-b--10 flex flex-row"> <div class="flex-shrink--0 margin-r--6"> <i class="icon icon-info icon-small"/> </div> <div> <div class="txt-size--13">Quality filter {{qualityFilterText}}</div> {{_i}}Improves the quality of Tweets you\'ll see.{{/i}} <a rel="url noopener noreferrer" target="_blank" href="https://twitter.com/settings/notifications_timeline"> {{_i}}Update your preferences on Twitter.com{{/i}}`,
	"mustaches.menus.search_accordion": `{{#action}} <div class="js-accordion-item facet-type facet-type-action {{#isExpanded}}is-expanded is-active{{/isExpanded}}"> {{>menus/accordion_header}} <div class="js-action-filter js-accordion-panel accordion-panel"> </div> </div> {{/action}} {{#content}} <div class="js-accordion-item facet-type facet-type-content {{#isExpanded}}is-expanded is-active{{/isExpanded}}"> {{>menus/accordion_header}} <div class="js-content-filter js-accordion-panel accordion-panel"> `,
	"mustaches.menus.search_action_form": `<div class="padding-l--10 control-s"> <div class="control-group"> {{#available.showMentions}} <div class="controls margin-l--0 {{^available.showMentions}}is-hidden{{/available.showMentions}}"> <label class="txt-mute"> <input class="js-show-mentions" type="checkbox" value="mentions" {{#checked.showMentions}}checked="checked"{{/checked.showMentions}} /> <i class="icon icon-small-valigned icon-mention icon-mention-color"></i> {{_i}}Mentions{{/i}} </label> </div> {{/available.showMentions}} {{#available.showQuoted}} `,
	"mustaches.menus.search_content_form": `<div class="padding-hl control-s"> <div class="control-group"> <label class="control-label txt-mute">{{_i}}Showing{{/i}}</label> <div class="controls"> <select class="js-containing" data-title="type"> {{#containingOptions}} {{^hidden}} <option value="{{value}}">{{title}}</option> {{/hidden}} {{/containingOptions}} </select> </div> </div> {{#withMatching}} <div class="control-group"> <label class="control-label txt-mute">{{_i}}Matching{{/i}}</label> {{>search_input}} </div> {{/withMatching}} {{#withExcluding}}`,
	"mustaches.menus.search_datetime_form": `<div class="control-group"> <label class="control-label txt-mute">{{_i}}From{{/i}}</label> <div class="controls"> <div class="js-from-datepicker-holder search-input-control" /> </div> </div> <div class="control-group"> <label class="control-label txt-mute">{{_i}}To{{/i}}</label>`,
	"mustaches.menus.search_engagement_form": `value="{{minFavorites}}" inputmode="numeric" /> <i class="icon icon-small-valigned icon-favorite padding-h--2"></i> {{_i}}likes{{/i}} </div> </label> <label> <div class="control-label">{{_i}}and at least{{/i}}</div> <div class="controls"> <input type="text" data-title="replies" class="js-min-replies frm-input-3-digit" value="{{minReplies}}" inputmode="numeric" /> <i class="icon icon-small-valigned icon-reply padding-h--2"></i> {{_i}}replies{{/i}} </div> </label> </div> </div>`,
	"mustaches.menus.search_user_form": `"js-tweets-from-me margin-txs" data-title="from_me"> {{#myAccounts}} <option value="{{value}}" {{#isDefault}}selected="selected"{{/isDefault}}>{{title}}</option> {{/myAccounts}} </select> </div> </div> <div class="control-group"> <label class="control-label txt-mute">{{_i}}Mentioning{{/i}}</label> <div class="controls"> <select class="js-mentioning" data-title="mentioning"> {{#mentioningOptions}} <option value="{{value}}">{{title}}</option> {{/mentioningOptions}} </select> </div> <div class="controls">`,
	"mustaches.menus.topbar_menu": ` {{/isTouchDevice}} <li class="is-selectable"> <a href="#" data-action="searchOperatorList">{{_i}}Search tips{{/i}}</a> </li> <li class="is-selectable"> <a href="#" data-action="globalSettings">{{_i}}Settings{{/i}}</a> </li> {{#showUpdateAvailable}} <li class="drp-h-divider"></li> <li class="is-selectable margin-v---6"> <a href="#" data-action="updateAvailable" class="update-available-item padding-v--10"> {{_i}}Update TweetDeck{{/i}} </a> </li> {{/showUpdateAvailable}} {{#showDisableDogfood}}`,
	"mustaches.menus.user_results": `<div class="js-dropdown-container scroll-v {{#styledScrollbar}}scroll-styled-v{{/styledScrollbar}} scroll-alt column-scroller column-background-fill margin-bs height-p--100 br--6"> {{#users}} {{<stream_item}} {{$content}} {{> account_summary }} {{/content}} {{/stream_item}} {{/users}} </div>`,

	"mustaches.modal": `<div class="js-modal-panel mdl s-tall-fixed {{$modal_class}}{{/modal_class}} {{#loading}}is-loading{{/loading}}"> {{#loading}} <img src="{{#asset}}/global/backgrounds/spinner_large_white.gif{{/asset}}" alt="{{_i}}Loading…{{/i}}" /> {{/loading}} {{^loading}} {{> modal_header}} <div class="mdl-inner"> <div class="mdl-content js-mdl-content {{^no_horiz_flow_container}}horizontal-flow-container{{/no_horiz_flow_container}}"> {{$content}}default content{{/content}} </div> <footer class="mdl-buttonbar"> {{$footer_content}}{{/footer_content}} `,
	"mustaches.modal.modal_context": `<div class="js-modal-context {{#withClickTrap}}js-click-trap{{/withClickTrap}} {{#withNonDismissible}}js-non-dismissible{{/withNonDismissible}} overlay overlay-super scroll-v"> <div class="js-modal-inner mdl margin-v--20 s-fluid"> {{#withHeader}} {{> modal/modal_context_header}} {{/withHeader}} {{#withDismissButton}} <a href="#" class="js-dismiss mdl-dismiss link-normal-dark"><i class="icon icon-close txt-size--18"></i></a> {{/withDismissButton}} <div class="js-modal-content modal-content {{#withBorder}}modal-content`,
	"mustaches.modal.modal_context_footer": `<footer class="padding-axl no-collapse {{#withCenteredFooter}}txt-center{{/withCenteredFooter}}"> {{#withDoneButton}} <button class="js-dismiss Button--primary"> `,
	"mustaches.modal.modal_context_header": `<header class="js-drag-handle padding-a--12 no-collapse mdl-header is-movable {{#withHeaderDivider}}mdl-header-divider{{/withHeaderDivider}}"> {{#title}} <h3 class="mdl-header-title">{{{title}}}</h3> {{/title}} </header>`,
	"mustaches.modal_header": `<header class="js-drag-handle padding-a--12 no-collapse mdl-header is-movable mdl-header-divider"> <h3 class="mdl-header-title `,
	"mustaches.new_custom_timeline_button": `<button class="Button--primary margin-al"> <i class="icon icon-plus icon-small-valigned"></i> <span class="label padding-ls">{{{buttonText}}}</span>`,
	"mustaches.number_ticker": `<div class="ticker-outer"> <span class="js-ticker-inner ticker-inner"> {{#values}}<span class="js-ticker-value">{{value}}</span><br>{{/values}} </span> </div>`,

	"mustaches.open_column_footer": `<button class="js-back btn btn-on-dark btn-back">&larr; {{_i}}Back{{/i}}</button> <span class="pull-right"> <button class="js-add-column Button--primary"><i class="add"></i>{{_i}}Add column{{/i}}</button> </span>`,
	"mustaches.open_column_home": `{#newColumnType}} <div class="margin-t--4"> <span class="bg-color-twitter-yellow color-twitter-white txt-size--9 txt-uppercase letter-spacing--1 padding-v--3 padding-h--7 br--14">{{_i}}New{{/i}}</span> </div> {{/newColumnType}} {{#premiumColumnType}} <div class="margin-t--4"> <span class="bg-color-twitter-deep-blue color-twitter-white txt-size--9 txt-uppercase letter-spacing--1 padding-v--3 padding-h--7 br--14">{{_i}}Beta{{/i}}</span> </div> {{/premiumColumnType}} {{#attribution}}`,
	"mustaches.open_column_list_group": `{{#isFilterable}} <input type="search" class="js-search-filter width-p--85 margin-b--8 margin-h--8 padding-v--0 padding-h--8" placeholder="{{_i}}Search{{/i}}" /> {{/isFilterable}} <p class="js-no-match padding-v--11 padding-h--12 txt-mute is-hidden">{{_i}}No{{/i}} {{itemType}} {{_i}}match that name{{/i}}</p> {{#title}}<h3 class="js-title {{#isHidden}}is-hidden{{/isHidden}}">{{title}}</h3>{{/title}} <ul class="js-list-container {{className}}"></ul>`,
	"mustaches.open_column_list_multi_group": `<div class="lst-group"> {{#groups}} {{>open_column_list_group}} {{/groups}} </div>`,
	"mustaches.open_column_list_with_header": `<div class="lst-group"> {{>open_column_list_group}} </div>`,
	"mustaches.open_column_modal": `<div class="js-modal-panel mdl s-tall-fixed "> {{> modal_header}} <div class="mdl-inner"> <div class="mdl-content js-mdl-content"> </div> <footer class="mdl-buttonbar"> </footer> </div> </div>`,
	"mustaches.open_column_temp_help": `<div class="l-table"> <div class="l-cell mdl-placeholder txt-size--16"> <p>{{helpText}}</p> </div> </div>`,
	"mustaches.open_split_menu": `<div class="l-column mdl-column mdl-column-med"> <div class="js-left-pinned pin-top-full-width {{#hasAddMultipleUsersButton}}width-p--85{{/hasAddMultipleUsersButton}}"></div> {{#hasAddMultipleUsersButton}} <button class="js-add-multiple js-show-tip add-multiple btn Button--tertiary btn-round btn-on-dark" data-title="Add multiple users"><i class="icon icon-small icon-user-team-mgr"></i></button> {{/hasAddMultipleUsersButton}} <div class="l-column-scrollv scroll-v `,
	"mustaches.overlay": `<div class="overlay is-hidden"></div>`,
	"mustaches.participants_tooltip": `<div class="js-tooltip margin-b--5 padding-h--5"> {{#title}}<b class="txt-size--14 block padding-v--10 conversation-tooltip-title">{{{title}}}</b>{{/title}} {{#participants}}`,
	"mustaches.popover": `<div class="js-popover popover br-1 bs-1 is-hidden"> <div class="caret"> <span class="caret-outer"></span> <span class="caret-inner"></span> </div> <div class="js-popover-content scroll-none"></div> </div>`,
	"mustaches.profile.profile_full": `<div class="media-item profile-bg-strip" style="background-image: url({{profileBannerURL}})"></div> <div class="profile-full padding-hxl padding-bl"> <div class="profile-full-header cf pin-top"> <a class="prf-img profile-full-avatar obj-left link-clean" href="{{getProfileURL}}" target="_blank" data-user-name="{{screenName}}" rel="user"> <img src="{{biggerProfileImageURL}}" class="avatar size48 avatar-border--2"> </a> <div class="nbfc"> <div class="profile-follow-button"> {{>follow_button}}`,
	"mustaches.profile_card_bio": `<div class="prf-bio"> <p class="bio">{{{bio}}}</p> </div>`,
	"mustaches.profile_card_stats": `<div class="prf-meta cf"> <div class="prf-follow-state padding-al"> {{> follow_button}} </div> {{#profile}} <ul class="prf-stats"> <li> <a href="https://twitter.com/{{screenName}}" data-action="open" data-type="tweets" class="js-action-url" target="_blank"> {{_i}}Tweets{{/i}} <strong>{{prettyStatusesCount}}</strong> </a> </li> <li> <a href="{{getFriendURL}}" class="js-action-url" target="_blank"> {{_i}}Following{{/i}} <strong>{{prettyFriendsCount}}</strong> </a> </li> <li> <a href="{{getFollowerURL}}"`,
	"mustaches.report_flow": `<iframe class="report-flow" src="{{url}}"></iframe>`,
	"mustaches.report_message_options": `{{^isFinished}} {{^isGroupConversation}} <p class="txt-size--16 padding-axl mdl-header-divider">{{_i}}Are you sure? The {{reportSource}} will be deleted from your inbox, and @{{screenName}} cannot message you until you message them first.{{/i}}</p> {{/isGroupConversation}} {{#isGroupConversation}} <p class="txt-size--16 padding-axl mdl-header-divider">{{_i}}Are you sure? The {{reportSource}} will be deleted from your inbox and you cannot be added to this group again.{{/i}}</p>`,
	"mustaches.report_tweet_options": `<fieldset> <legend>{{_i}}Report Tweet options{{/i}}</legend> <div class="padding-hl padding-tl"> <label class="radio margin-bl"> <input checked type="radio" name="report-options" value="spam" class="js-report-option"> <b class="txt-size--14">{{_i}}Spam{{/i}}</b> <p>{{_i}}This Tweet may be spam or from a spam account{{/i}}</p> </label> <label class="radio margin-bl"> <input type="radio" name="report-options" value="compromised" class="js-report-option"> <b class="txt-size--14">{{_i}}Compromised{{/i}}</b>`,
	"mustaches.report_tweet_options_abusive": `<p>{{_i}}Please choose the topic that best defines your issue. Once you complete and the submit the form your report will be filed with Twitter.{{/i}}</p> <ul class="margin-txl margin-lxl"> <li class="margin-bm"> <a href="https://support.twitter.com/forms/impersonation?reported_username={{screenName}}&amp;reported_tweet_id={{tweetId}}" target="_blank" data-scribe="impersonation" class="abuse-link">Impersonation</a> </li> <li class="margin-bm"> <a href="https://support.twitter.com/forms/trademark?reported_u`,
	"mustaches.scheduled_hint": `<div class="{{#showHint}}anim anim-fade-in{{/showHint}}{{^showHint}} is-hidden{{/showHint}}"> {{#showHint}}{{_i}}Your scheduled Tweet will send even if TweetDeck is not running at the time.{{/i}}{{/showHint}} </div>`,
	"mustaches.search.search_in_popover": `<form class="js-search-form app-search app-search-in-popover margin-a--10"> <label class="is-vishidden">{{_i}}Search{{/i}}</label> {{>search_input}} </form> `,
	"mustaches.search.search_results": `<div class="js-search-results-container search-results-container is-hidden height-vh--100"> <div class="js-user-results user-results"></div> </div>`,
	"mustaches.search_input": `<div class="js-search-input-control search-input-control {{searchInputControlClass}} {{#isControl}}controls{{/isControl}}"> <input type="text" class="{{searchInputClassName}} search-input" data-title="{{searchInputTitle}}" placeholder="{{searchInputPlaceholder}}" value="{{searchInputValue}}"> <a href="#" class="js-perform-search txt-size--14 search-input-perform-search" tabindex="-1"> <i class="icon icon-search txt-size--16"></i> </a> <a href="#" class="js-clear-search `,

	"mustaches.search_no_tweets_placeholder": `<div class="list-placeholder l-table pin-all"> <div class="l-cell"> {{#isDropTarget}} <p class="txt-size--16"><i class="icon icon-move icon-tb"></i> <span>{{_i}}Drag Tweets into this Collection{{/i}}</span></p> {{/isDropTarget}} {{^isDropTarget}} <p class="txt-size--16">{{_i}}No recent Tweets.{{/i}}<br />{{_i}}New Tweets will appear here.{{/i}}</p> {{/isDropTarget}} </div> {{#withAddByUrl}} <p class="pin-bottom-full-width txt-center">{{_i}}Or add by URL{{/i}}</p> {{/withAddByUrl}} </div>`,
	"mustaches.search_no_users_placeholder": `<div class="list-placeholder"> <p>{{_i}}No users found.{{/i}}</p> </div>`,
	"mustaches.search_operator_list": `<div class="padding-v--20"> <table class="search-operator-list l-table"> <thead> <tr> <th class="{{tblLeftItemClass}}">{{_i}}Operator{{/i}}</th> <th class="{{tblRightItemClass}}">{{_i}}Find Tweets...{{/i}}</th> </tr> </thead> <tbody> {{#searchOperators}} {{>search_operator_list_item_group}} {{/searchOperators}} </tbody> </table> <div> {{#advancedSearches}} <div> <h4 class="{{sectionHeaderClass}}">{{sectionTitle}}</h4> <p class="{{advancedSearchContentClass}} txt-italic">{{sectionExplanation}}</p> `,
	"mustaches.search_operator_list_item": `<tr class="search-tip-item-hover txt-size--12"> <td class="{{tblLeftItemClass}}">{{query}}</td> <td class="{{tblRightItemClass}} query flex flex-`,
	"mustaches.search_operator_list_item_group": `{{#sectionTitle}} <tr> <th colspan="2" class="{{sectionHeaderClass}}">{{sectionTitle}}</th> </tr> {{#sectionOperators}} {{>search_operator_list_item}} {{/sectionOperators}} {{/sectionTitle}}`,

	"mustaches.settings.account_settings": `<div class="js-accounts-column-holder column-holder txt-size--14"> <div class="js-account-manager-container column-panel accounts-drawer border-box flex flex-column"> <header class="drawer-header padding-lxl flex-shrink--0"> <h1 class="column-title"> <span class="drawer-header-title block drawer-column-header-title">{{_i}}Accounts{{/i}}</span> </h1> <a class="js-drawer-close column-close-link color-twitter-darker-gray" href="#" data-action="options"> <i class="icon icon-close icon-center-24"></i>`,
	"mustaches.settings.account_settings_detail": `{{#requireConsent}} <div data-testid="gdprConsentMessage" class="border-a--2 br--4 border-color-twitter-blue color-twitter-deep-black padding-a--15 txt-size--12"> <h2 class="color-twitter-blue txt-size--14 txt-bold">{{_i}}Updates to the Twitter Terms of Service and Privacy Policy{{/i}}</h2> <p class="nbfc txt-size--13 padding-tm"> {{_i}}Twitter is updating its{{/i}} <a href="https://twitter.com/tos#new" target="_blank"> {{_i}}Terms{{/i}} </a> {{_i}}and{{/i}} <a href="https://twitter.com/privacy" target="_blank">{{_i}}Privacy Policy{{/i}}</a>. {{_i}}To continue contributing to this team account in TweetDeck, you or the team account’s owner need to visit Twitter’s website and agree to the updated Terms and Privacy Policy.{{/i}} </p> <p class="nbfc txt-size--13 padding-tm"> {{_i}}For more information, visit the{{/i}} <a href="https://help.twitter.com/rules-and-policies/update-privacy-policy" target="_blank">{{_i}}Help Center{{/i}}</a>. </p> </div> {{/requireConsent}} {{#withManageTeam}} `,
	"mustaches.settings.account_settings_join_team": `<a href="#" class="js-log-in-account txt-size--13 padding-hxl txt-line-height--40">{{_i}}Link another account you own{{/i}}</a>`,
	"mustaches.settings.account_settings_login_account": `<div class="js-accordion-item js-account-settings-row js-account-settings-summary account-settings-row account-settings-row {{#isSoleAccount}}is-expanded{{/isSoleAccount}}" data-account-key="{{accountKey}}" data-user-id="{{userId}}"> <div class="js-account-profile-header account-profile-header"></div> <div class="padding-h--16 padding-b--16 margin-t---24 account-settings-bb hyphenate"> <div class="flex flex-row"> <a href="{{getProfileURL}}" class="txt-size--0 " rel="user" target="_blank"> `,
	"mustaches.settings.account_settings_remove_account": `{{#isRemovable}} <button {{#notRemovable}}title="{{notRemovableMessage}}"{{/notRemovable}} class="js-account-action js-show-tip btn Button--tertiary btn-on-dark txt-size--12{{#notRemovable}} is-disabled{{/notRemovable}}" data-action="removeCheck" data-account-key="{{accountKey}}"> <span class="label">{{_i}}Leave team{{/i}}</span> </button> <div class="js-account-remove-check account-remove-check cf margin-tm padding-axl br--4 padding-l--20 margin-l---20"> <div class="account-remove-check-message `,
	"mustaches.settings.account_settings_row": `<div data-testid="accountRow" class="js-accordion-item js-account-settings-row padding-vxl cf account-row-separator-b account-settings-row position-rel" data-account-key="{{accountKey}}" data-user-id="{{userId}}"> <div data-testid="accountSummary" class="js-accordion-toggle-view position-rel padding-hxl is-actionable flex flex-row flex-align--center"> <div class="js-account-settings-summary nbfc flex-auto margin-r--3"> {{>account_settings_account_summary}} </div> {{#requireConsent}} `,
	"mustaches.settings.global_setting_filter": `<fieldset id="global_filter_settings"> <legend class="frm-legend">{{_i}}Mute Settings{{/i}}</legend> <div class="control-group"> <label for="filter-types" class="control-label">{{_i}}Mute{{/i}}</label> <div class="controls"> <select name="filter" class="js-filter-types"> <option value="phrase">{{_i}}Words or phrases{{/i}}</option> <option value="source">{{_i}}Tweet Source{{/i}}</option> </select> </div> </div> <div class="control-group"> <label for="filter-input" class="control-label">{{_i}}Matching{{/i}}`,
	"mustaches.settings.global_setting_filter_add_btn": `<button name="add-filter" class="js-add-filter btn-on-dark" {{^addFilterButtonEnabled}}disabled{{/addFilterButtonEnabled}}>{{_i}}Mute{{/i}}</button>`,
	"mustaches.settings.global_setting_filter_list": `<ul class="min-height--90"> {{#filters}} {{>settings/global_setting_filter_row}} {{/filters}} </ul>`,
	"mustaches.settings.global_setting_filter_row": `<li class="list-filter cf"> {{_i}}Muting {{getDisplayType}} {{>text/global_filter_value}}{{/i}} <input type="button" name="remove-filter" value="{{_i}}Remove{{/i}}" data-id="{{id}}" class="js-remove-filter small Button--danger"> </li>`,
	"mustaches.settings.global_setting_general": `<fieldset id="general_settings"> <legend>{{_i}}General Settings{{/i}}</legend> <div class="control-group"> <div> <i class="js-streaming-updates icon icon-small icon-toggle-off color-twitter-blue js-toggle-switch is-actionable align-top" `,
	"mustaches.settings.global_setting_link_shortening": `<fieldset id="services_settings" > <legend>{{_i}}Services Settings{{/i}}</legend> <div id="streaming-form" class="control-group"> <label for="link-shortening" class="control-label">{{_i}}Link Shortening{{/i}}</label> <div class="controls"> <select name="link-shortening" class="js-link-shortening"> <option value="twitter">Twitter</option> <option value="bitly">Bit.ly</option> </select> </div> </div> <div id="bitly-form" class="js-bitly-form"></div> </fieldset>`,
	"mustaches.settings.global_settings_modal": `<div class="l-column mdl-column mdl-column-sml"> <div class="l-column-scrollv scroll-v {{#styledScrollbar}}scroll-styled-v{{/styledScrollbar}} scroll-alt"> <ul class="lst-group js-setting-list"> {{#tabs}} {{> list_module_list_item}} {{/tabs}} </ul> </div> </div> <div class="l-column mdl-column mdl-column-lrg"> <div class="l-column-scrollv scroll-v {{#styledScrollbar}}scroll-styled-v{{/styledScrollbar}} scroll-alt mdl-col-settings"> <form action="#" id="global-settings" accept-charset="utf-8`,
	"mustaches.settings.invitations_panel": `{{#showInvitationPanel}} <div class="js-account-action js-account-settings-team-invitations padding-hxl padding-v--12 txt-size--13 color-twitter-darker-gray txt-bold position-rel account-row-separator-b flex flex-row flex-align--center is-actionable" data-action="showInvitations"> <span class="flex-grow--1">{{_i}}Team invitations{{/i}}</span> <div class="account-invitation-badge-container"> <span class="js-invitation-count numbered-badge bg-color-twitter-blue numbered-badge-account-invites" data-count={{invitationCount}}>{{invitationCount}}`,
	"mustaches.settings.link_shortening_bitly_form": `<div class="control-group"> <label for="bitly-email" class="control-label">{{_i}}Bit.ly Username{{/i}}</label> <div class="controls"> <input id="bitly-email" class="js-bitly-email" name="bitly-email" size="30" type="text" value="{{#bitlyAccount}}{{login}}{{/bitlyAccount}}"> </div> </div> <div class="control-group"> <label for="bitly-key" class="control-label">{{_i}}Bit.ly API Key{{/i}}</label> <div class="controls"> <input id="bitly-key" class="js-bitly-key" name="bitly-key" size="40" type="text" `,

	"mustaches.short_modal": `<div class="js-modal-panel mdl s-short"> {{> modal_header}} <div class="mdl-inner{{#modalClasses}} {{{modalClasses}}}{{/modalClasses}}"> <div class="mdl-content js-mdl-content horizontal-flow-container"> {{{content}}} </div> <footer class="{{^centeredFooter}}mdl-buttonbar{{/centeredFooter}}{{#centeredFooter}}padding-vxl txt-center{{/centeredFooter}}"> {{#hasDoneButton}} <button class="js-dismiss Button--primary pull-right"> <span class="label">{{_i}}Done{{/i}}</span> </button> {{/hasDoneButton}} </footer> </div> </div>`,
	// note to self: I was at m1659 at this point

	"mustaches.typeahead_dropdown.js": `<div class="js-typeahead-dropdown margin-t--6 scroll-v {{#styledScrollbar}}scroll-styled-v{{/styledScrollbar}}">`,

	"object-assign.js": `(c) Sindre Sorhus`,
	"react-dom.js": `* react-dom.production.`,
	"react-native.i18nManager.js": `i.default.canUseDOM&&document.documentElement&&document.documentElement.setAttribute&&document.documentElement`,
	"react.js": `* react.production.`,
	"react.scheduler.js": `* scheduler.production.`,
	"reactivex.audit.js": `.Observable.prototype.audit=`,
	"reactivex.auditTime.js": `.Observable.prototype.auditTime=`,
	"reactivex.concat.js": `.Observable.prototype.concat=`,
	"reactivex.concatMap.js": `.Observable.prototype.concatMap=`,
	"reactivex.count.js": `.Observable.prototype.count=`,
	"reactivex.debounce.js": `.Observable.prototype.debounce=`,
	"reactivex.debounceTime.js": `.Observable.prototype.debounceTime=`,
	"reactivex.defaultIfEmpty.js": `.Observable.prototype.defaultIfEmpty=`,
	"reactivex.delay.js": `.Observable.prototype.delay=`,
	"reactivex.delayWhen.js": `.Observable.prototype.delayWhen=`,
	"reactivex.dematerialize.js": `.Observable.prototype.dematerialize=`,
	"reactivex.distinct.js": `.Observable.prototype.distinct=`,
	"reactivex.distinctUntilChanged.js": `.Observable.prototype.distinctUntilChanged=`,
	"reactivex.distinctUntilKeyChanged.js": `.Observable.prototype.distinctUntilKeyChanged=`,
	"reactivex.do.js": `.Observable.prototype.do=`,
	"reactivex.elementAt.js": `.Observable.prototype.elementAt=`,
	"reactivex.every.js": `.Observable.prototype.every=`,
	"reactivex.exhaust.js": `.Observable.prototype.exhaust=`,
	"reactivex.exhaustMap.js": `.Observable.prototype.exhaustMap=`,
	"reactivex.expand.js": `.Observable.prototype.expand=`,
	"reactivex.flatMapTo.js": `.Observable.prototype.flatMapTo=`,
	"reactivex.filter.js": `.Observable.prototype.filter=`,
	"reactivex.finally.js": `.Observable.prototype.finally=`,
	"reactivex.find.js": `.Observable.prototype.find=`,
	"reactivex.findIndex.js": `.Observable.prototype.findIndex=`,
	"reactivex.first.js": `.Observable.prototype.first=`,
	"reactivex.groupBy.js": `.Observable.prototype.groupBy=`,
	"reactivex.ignoreElements.js": `.Observable.prototype.ignoreElements=`,
	"reactivex.isEmpty.js": `.Observable.prototype.isEmpty=`,
	"reactivex.last.js": `.Observable.prototype.last=`,
	"reactivex.let.js": `.Observable.prototype.let=`,
	"reactivex.map.js": `.Observable.prototype.map=`,
	"reactivex.mapTo.js": `.Observable.prototype.mapTo=`,
	"reactivex.materialize.js": `.Observable.prototype.materialize=`,
	"reactivex.max.js": `.Observable.prototype.max=`,
	"reactivex.merge.js": `.Observable.prototype.merge=`,
	"reactivex.mergeAll.js": `.Observable.prototype.mergeAll=`,
	"reactivex.mergeMap.js": `.Observable.prototype.mergeMap=`,
	"reactivex.mergeScan.js": `.Observable.prototype.mergeScan=`,
	"reactivex.min.js": `.Observable.prototype.min=`,
	"reactivex.multicast.js": `.Observable.prototype.multicast=`,
	"reactivex.observeOn.js": `.Observable.prototype.observeOn=`,
	"reactivex.onErrorResumeNext.js": `.Observable.prototype.onErrorResumeNext=`,
	"reactivex.pairwise.js": `.Observable.prototype.pairwise=`,
	"reactivex.partition.js": `.Observable.prototype.partition=`,
	"reactivex.pluck.js": `.Observable.prototype.pluck=`,
	"reactivex.publish.js": `.Observable.prototype.publish=`,
	"reactivex.publishBehavior.js": `.Observable.prototype.publishBehavior=`,
	"reactivex.publishReplay.js": `.Observable.prototype.publishReplay=`,
	"reactivex.publishLast.js": `.Observable.prototype.publishLast=`,
	"reactivex.race.js": `.Observable.prototype.race=`,
	"reactivex.reduce.js": `.Observable.prototype.reduce=`,
	"reactivex.repeat.js": `.Observable.prototype.repeat=`,
	"reactivex.repeatWhen.js": `.Observable.prototype.repeatWhen=`,
	"reactivex.retry.js": `.Observable.prototype.retry=`,
	"reactivex.retryWhen.js": `.Observable.prototype.retryWhen=`,
	"reactivex.sample.js": `.Observable.prototype.sample=`,
	"reactivex.sampleTime.js": `.Observable.prototype.sampleTime=`,
	"reactivex.scan.js": `.Observable.prototype.scan=`,
	"reactivex.sequenceEqual.js": `.Observable.prototype.sequenceEqual=`,
	"reactivex.share.js": `.Observable.prototype.share=`,
	"reactivex.shareReplay.js": `.Observable.prototype.shareReplay=`,
	"reactivex.single.js": `.Observable.prototype.single=`,
	"reactivex.skip.js": `.Observable.prototype.skip=`,
	"reactivex.skipLast.js": `.Observable.prototype.skipLast=`,
	"reactivex.skipUntil.js": `.Observable.prototype.skipUntil=`,
	"reactivex.skipWhile.js": `.Observable.prototype.skipWhile=`,
	"reactivex.startWith.js": `.Observable.prototype.startWith=`,
	"reactivex.subscribeOn.js": `.Observable.prototype.subscribeOn=`,
	"reactivex.switch.js": `.Observable.prototype.switch=`,
	"reactivex.switchMap.js": `.Observable.prototype.switchMap=`,
	"reactivex.switchMapTo.js": `.Observable.prototype.switchMapTo=`,
	"reactivex.take.js": `.Observable.prototype.take=`,
	"reactivex.takeLast.js": `.Observable.prototype.takeLast=`,
	"reactivex.takeUntil.js": `.Observable.prototype.takeUntil=`,
	"reactivex.takeWhile.js": `.Observable.prototype.takeWhile=`,
	"reactivex.throttle.js": `.Observable.prototype.throttle=`,
	"reactivex.throttleTime.js": `.Observable.prototype.throttleTime=`,
	"reactivex.timeInterval.js": `.Observable.prototype.timeInterval=`,
	"reactivex.timeout.js": `.Observable.prototype.timeout=`,
	"reactivex.timeoutWith.js": `.Observable.prototype.timeoutWith=`,
	"reactivex.timestamp.js": `.Observable.prototype.timestamp=`,
	"reactivex.toArray.js": `.Observable.prototype.toArray=`,
	"reactivex.toPromise.js": `.Observable.prototype.toPromise=`,
	"reactivex.window.js": `.Observable.prototype.window=`,
	"reactivex.windowTime.js": `.Observable.prototype.windowTime=`,
	"reactivex.windowToggle.js": `.Observable.prototype.windowToggle=`,
	"reactivex.windowWhen.js": `.Observable.prototype.windowWhen=`,
	"reactivex.withLatestFrom.js": `.Observable.prototype.withLatestFrom=`,
	"reactivex.zip.js": `.Observable.prototype.zip=`,
	"reactivex.zipAll.js": `.Observable.prototype.zipAll=`,
	"services.bitly.js": `TD.services.bitly=((`,
	"services.Conversations.js": `TD.services.Conversations=function(`,
	"services.CustomTimeline.js": `TD.services.CustomTimeline=function(`,
	"services.DataminrAlert.js": `TD.services.DataminrAlert=function(`,
	"services.ScheduledTweet.js": `TD.services.ScheduledTweet=function(`,
	"services.ScheduledTweetGroup.js": `TD.services.ScheduledTweetGroup=u,`,
	"services.TweetDeckClient.js": `TD.services.TweetDeckClient=function(`,
	"services.TwitterClient.js": `TD.services.TwitterClient.prototype.processDeleteChirpEvent`,
	"services.TwitterActionFavoritedInteraction.js": `TD.services.TwitterActionFavoritedInteraction=function(e`,
	"services.TwitterActionFavorite.js": `TD.services.TwitterActionFavorite=function(e`,
	"services.TwitterAction.js": `TD.services.TwitterAction=function(e`,
	"services.TwitterActionListCreated.js": `TD.services.TwitterActionListCreated=function(e`,
	"services.TwitterActionListMemberAdded.js": `TD.services.TwitterActionListMemberAdded=function(e`,
	"services.TwitterActionFollow.js": `TD.services.TwitterActionFollow=function(e`,
	"services.TwitterActionQuotedTweet.js": `TD.services.TwitterActionQuotedTweet=function(e`,
	"services.TwitterActionMultiListMemberAdded.js": `TD.services.TwitterActionMultiListMemberAdded=function(e`,
	"services.TwitterActionMention.js": `TD.services.TwitterActionMention=function(e`,
	"services.TwitterActionOnTweet.js": `TD.services.TwitterActionOnTweet=function(e`,
	"services.TwitterActionRetweet.js": `TD.services.TwitterActionRetweet=function(e`,
	"services.TwitterActionRetweetedInteraction.js": `TD.services.TwitterActionRetweetedInteraction=function(e`,
	"services.TwitterConversation.js": `TD.services.TwitterConversation=function(`,
	"services.TwitterConversationReadEvent.js": `TD.services.TwitterConversationReadEvent=function(e`,
	"services.TwitterConversationFailedParticipantsEvent.js": `TD.services.TwitterConversationFailedParticipantsEvent=function(e`,
	"services.TwitterDeletedUser.js": `TD.services.TwitterDeletedUser=function(e`,
	"services.TwitterList.js": `TD.services.TwitterList=function(e`,
	"services.TwitterUser.js": `TD.services.TwitterUser=function(e`,
	"services.TwitterSearchParser.js": `TD.services.TwitterSearchParser=function(e`,
	"services.TwitterStatus.js": `TD.services.TwitterStatus=function(e`,
	"services.TwitterMedia.js": `TD.services.TwitterMedia=function(){}`,
	"storage.Account.js": `TD.storage.Account=function(`,
	"storage.Client.js": `TD.storage.Client=function(`,
	"storage.ClientController.js": `TD.storage.ClientController=(`,
	"storage.Column.js": `TD.storage.Column=function(`,
	"storage.ColumnController.js": `TD.storage.ColumnController=(`,
	"storage.Feed.js": `TD.storage.Feed=(`,
	"storage.FeedController.js": `TD.storage.FeedController=(`,
	"storage.notification.js": `TD.storage.notification=(`,
	"storage.SobjController.js": `TD.storage.SobjController=(`,
	"storage.StoredDelta.js": `TD.storage.StoredDelta=function(`,
	"storage.StoredObj.js": `TD.storage.StoredObj=function(`,
	"sync.controller.js": `TD.sync.controller=function(`,
	"sync.tdapi.js": `TD.sync.tdapi=function(`,
	"sync.trace.js": `TD.sync.trace=(`,
	"ui.debug.js": `TD.debug={`,
	"ui.main.js": `TD.ui.main=((n={})`,
	"ui.openColumn.js": `TD.ui.openColumn=function(`,
	"ui.updates.js": `TD.ui.updates=function(`,
	"vo.ActionFilter.js": `TD.vo.ActionFilter=function(`,
	"vo.Column.js": `TD.vo.Column=function(`,
	"vo.EngagementFilter.js": `TD.vo.EngagementFilter=function(`,
	"vo.Filter.js": `TD.vo.Filter=function(`,
	"vo.SearchFilter.js": `TD.vo.SearchFilter=function(`,
	"vo.UserFilter.js": `TD.vo.UserFilter=function(`
}
