exports.deobf_rules = {
	"jquery.js": "Sizzle CSS Selector Engine",
	"flight.js": "/*! Flight v",
	"react-dom-native-dependencies.js": "* react-dom-native-dependencies",
	"react-dom.js": "* react-dom.production.",
	"react.js": "* react.production.",
	"react.scheduler.js": "* scheduler.production.",
	"object-assign.js": "(c) Sindre Sorhus",
	"jquery.tools.dateinput.js": "Dateinput - <input type=\"date\" />",
	"leaflet-src.js": "return!this._container.getElementsByClassName(\"leaflet-zoom-animated\").length",
	"moment.js": " && !e.invalidMonth && !e.invalidWeekday",
	"core-js.object-define-property.js": " throw TypeError(\"Accessors not supported!\");",
	"globalRenderOptions.js": "TD.globalRenderOptions=(n={",
	"minWrapperVersion.js": "TD.minWrapperVersionMac=\"\"",
	"services.Conversations.js": "TD.services.Conversations=function(",
	"services.CustomTimeline.js": "TD.services.CustomTimeline=function(",
	"services.DataminrAlert.js": "TD.services.DataminrAlert=function(",
	"services.ScheduledTweet.js": "TD.services.ScheduledTweet=function(",
	"services.ScheduledTweetGroup.js": "TD.services.ScheduledTweetGroup=u,",
	"services.TweetDeckClient.js": "TD.services.TweetDeckClient=function(",
	"services.TwitterClient.js": "TD.services.TwitterClient.prototype.processDeleteChirpEvent",
	"services.TwitterActionFavoritedInteraction.js": "TD.services.TwitterActionFavoritedInteraction=function(e",
	"services.TwitterActionFavorite.js": "TD.services.TwitterActionFavorite=function(e",
	"services.TwitterAction.js": "TD.services.TwitterAction=function(e",
	"services.TwitterActionListCreated.js": "TD.services.TwitterActionListCreated=function(e",
	"services.TwitterActionListMemberAdded.js": "TD.services.TwitterActionListMemberAdded=function(e",
	"services.TwitterActionFollow.js": "TD.services.TwitterActionFollow=function(e",
	"services.TwitterActionQuotedTweet.js": "TD.services.TwitterActionQuotedTweet=function(e",
	"services.TwitterActionMultiListMemberAdded.js": "TD.services.TwitterActionMultiListMemberAdded=function(e",
	"services.TwitterActionMention.js": "TD.services.TwitterActionMention=function(e",
	"services.TwitterActionOnTweet.js": "TD.services.TwitterActionOnTweet=function(e",
	"services.TwitterActionRetweet.js": "TD.services.TwitterActionRetweet=function(e",
	"services.TwitterActionRetweetedInteraction.js": "TD.services.TwitterActionRetweetedInteraction=function(e",
	"services.TwitterConversation.js": "TD.services.TwitterConversation=function(",
	"services.TwitterConversationReadEvent.js": "TD.services.TwitterConversationReadEvent=function(e",
	"services.TwitterConversationFailedParticipantsEvent.js": "TD.services.TwitterConversationFailedParticipantsEvent=function(e",
	"services.TwitterDeletedUser.js": "TD.services.TwitterDeletedUser=function(e",
	"services.TwitterList.js": "TD.services.TwitterList=function(e",
	"services.TwitterUser.js": "TD.services.TwitterUser=function(e",
	"services.TwitterSearchParser.js": "TD.services.TwitterSearchParser=function(e",
	"services.TwitterMedia.js": "TD.services.TwitterMedia=function(){}",
	"ui.column.js": "TD.ui.column=function(",
	"ui.debug.js": "TD.debug={",
	"ui.main.js": "TD.ui.main=((n={})",
	"ui.openColumn.js": "TD.ui.openColumn=function(",
	"ui.updates.js": "TD.ui.updates=function()"
}
